-- #############################################################################
-- #  2TDSX_2024_CodigoSql_Integrantes.sql
-- #  KURA - Sistema de Gestao de Continuidade Veterinaria (Clyvo Vet)
-- #  FIAP Challenge 2026 - Sprint 3
-- #  Disciplina: Mastering Relational and Non-Relational Database
-- #############################################################################
-- #
-- #  INTEGRANTES (ordem alfabetica pelo primeiro nome):
-- #    - Clayton Alves ................ RM562285
-- #    - Felipe Ferrete Soares Lemes .. RM562999
-- #    - Guilherme Sola ............... RM563674
-- #    - Gustavo Bosak ............... RM566315
-- #    - Nikolas Brisola ............. RM564371
-- #  NOTA: a rubrica exige NOMES COMPLETOS. Apenas Felipe tem nome completo
-- #  registrado em arquivo; os outros 4 aparecem como nome + sobrenome. Os nomes
-- #  completos e o "X"/"2024" do nome deste arquivo dependem de confirmacao
-- #  humana (professor + integrantes) - ver o PDF de entrega (SD-09).
-- #
-- #  Turma:      2TDSX  (2o ano, Analise e Desenvolvimento de Sistemas)
-- #  Data:       2026-09-08
-- #  Banco:      Oracle Database 19c Enterprise Edition (parceria FIAP x Oracle)
-- #
-- #############################################################################
-- #  ESCOPO DESTE ARQUIVO
-- #
-- #  Este arquivo e o SCHEMA CONSOLIDADO do sistema KURA no estado da migration
-- #  Flyway V19 - 30 tabelas - MAIS os 5 objetos PL/SQL e a tabela de auditoria
-- #  exigidos pela Sprint 3.
-- #
-- #  O schema real do KURA e mantido por 19 migrations Flyway no repositorio
-- #  backend-tutor-java (db/migration + db/migration-oracle). Este arquivo e a
-- #  CONSOLIDACAO dessas 19 migrations num unico script executavel: cada tabela
-- #  ja nasce no estado final, com todas as ~75 alteracoes posteriores (ALTER
-- #  TABLE) ja aplicadas. Ele reflete o banco real, com as incoerencias herdadas
-- #  (sequences orfas, estrategia dupla de PK em AGENDAMENTO) - um script "mais
-- #  limpo" que o banco real seria um script que nao corresponde ao sistema.
-- #
-- #  AMBIENTE DE EXECUCAO: schema de aluno no Oracle FIAP. Esse schema e
-- #  COMPARTILHADO por varias disciplinas de banco (ha ~70 tabelas de outros
-- #  trabalhos no mesmo schema). Por isso o BLOCO 1 (limpeza) derruba SOMENTE os
-- #  objetos do KURA, por nome - nunca um "DROP" generico. E por isso a
-- #  conferencia de contagem e feita por NOME (WHERE table_name IN (...)), nao
-- #  por SELECT COUNT(*) FROM user_tables.
-- #
-- #  ESTRUTURA:
-- #    BLOCO 0  - Cabecalho e configuracao de sessao (este bloco)
-- #    BLOCO 1  - Limpeza idempotente (DROP dos objetos KURA, por nome)
-- #    BLOCO 2  - 29 sequences
-- #    BLOCO 3  - 30 tabelas (estado V19), em ordem de dependencia de FK
-- #    BLOCO 4  - Indices
-- #    BLOCO 5  - 2 views
-- #    BLOCO 6  - Tabela de auditoria da Sprint 3 (AUDITORIA_COBRANCA)
-- #    BLOCO 7  - Carga de dados (>= 5 registros por tabela) .......... [SD-03]
-- #    BLOCO 8  - Funcoes: FN_COBRANCA_TO_JSON, FN_CALCULAR_SCORE_URGENCIA [SD-04/06]
-- #    BLOCO 9  - Procedimentos: PRC_LISTAR_COBRANCAS_JSON, PRC_RELATORIO_COBRANCAS [SD-04/05]
-- #    BLOCO 10 - Trigger: TRG_AUDITORIA_COBRANCA .................... [SD-07]
-- #    BLOCO 11 - Bloco de demonstracao (caminho feliz + excecoes) ... [SD-08]
-- #
-- #  NENHUMA credencial, host, senha ou connection string neste arquivo.
-- #  Todos os dados de carga (BLOCO 7) sao ficticios e declarados como tais.
-- #############################################################################

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET LINESIZE 200
SET PAGESIZE 1000
WHENEVER SQLERROR CONTINUE


-- #############################################################################
-- #  BLOCO 1 - LIMPEZA IDEMPOTENTE (namespaced)
-- #
-- #  Finalidade: tornar o script re-executavel. Derruba, POR NOME, apenas os
-- #  objetos do KURA e da tentativa anterior de Sprint 3 - nunca objetos de
-- #  outras disciplinas presentes no mesmo schema de aluno.
-- #
-- #  Cada DROP e isolado num bloco PL/SQL com "EXCEPTION WHEN OTHERS THEN NULL":
-- #  se o objeto nao existe (primeira execucao, ou schema limpo), o erro
-- #  (ORA-00942 / ORA-02289 / ORA-04043 / ORA-04080) e engolido e o script
-- #  segue. TABLE usa CASCADE CONSTRAINTS para dispensar a ordem inversa de FK.
-- #
-- #  Objetos de outras disciplinas que porventura referenciem tabelas KURA
-- #  (nao ha nenhum conhecido) ou objetos PL/SQL da Sprint 1/2 do proprio KURA
-- #  (PRC_INSERT_*, REQ 1-4) podem ficar INVALID apos este bloco - isso e
-- #  esperado e nao e erro: recompilam sozinhos ou ao rodar o schema da Sprint
-- #  anterior. A conferencia de aceite da Sprint 3 olha so os objetos deste
-- #  arquivo.
-- #############################################################################

PROMPT
PROMPT === BLOCO 1: limpeza dos objetos KURA (idempotente) ===

-- --- 1.1 Trigger e objetos PL/SQL da Sprint 3 (nova e a tentativa anterior) ---
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDITORIA_COBRANCA';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_AGENDAMENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_LISTAR_COBRANCAS_JSON';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_RELATORIO_COBRANCAS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_EXPORTA_PETS_JSON';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_TOTALIZA_AGENDA_MINUTOS';EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_COBRANCA_TO_JSON';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CALCULAR_SCORE_URGENCIA';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FNC_JSON_PET';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FNC_VALIDA_SENHA_TUTOR';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_CLINICA';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_ESPECIE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_VETERINARIO';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_TUTOR';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_PET';             EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --- 1.2 Views KURA (recriadas no BLOCO 5) ---
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TIMELINE_PET';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_VACINAS_VENCENDO';   EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --- 1.3 Tabelas KURA + satelites da Sprint 1/2 (CASCADE CONSTRAINTS: ordem de FK dispensada) ---
-- Tabela de auditoria da Sprint 3 (nova e a da tentativa anterior)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_COBRANCA CASCADE CONSTRAINTS PURGE';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_AGENDAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Satelites academicos KURA da Sprint 1/2 (confirmados no schema; nao pertencem ao V19)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRESCRICAO_MEDICAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_SENHAS CASCADE CONSTRAINTS PURGE';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_CONSULTA CASCADE CONSTRAINTS PURGE';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- As 30 tabelas do schema V19 (nivel 5 -> nivel 1 da topologia de FK)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COBRANCA CASCADE CONSTRAINTS PURGE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONSULTA CASCADE CONSTRAINTS PURGE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXAME CASCADE CONSTRAINTS PURGE';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VACINA CASCADE CONSTRAINTS PURGE';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRESCRICAO CASCADE CONSTRAINTS PURGE';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOCUMENTO CASCADE CONSTRAINTS PURGE';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AGENDAMENTO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TRIAGEM_LUNA CASCADE CONSTRAINTS PURGE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALERTA_TEMPERATURA CASCADE CONSTRAINTS PURGE';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EVENTO_CLINICO CASCADE CONSTRAINTS PURGE';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTA_TUTOR CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TUTOR_PET CASCADE CONSTRAINTS PURGE';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTIFICACAO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INTERACAO_CANAL CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LEITURA_TEMPERATURA CASCADE CONSTRAINTS PURGE';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO_CLINICA CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONSENTIMENTO CASCADE CONSTRAINTS PURGE';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVITE_TUTOR CASCADE CONSTRAINTS PURGE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PET CASCADE CONSTRAINTS PURGE';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SERVICO_PRECO CASCADE CONSTRAINTS PURGE';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DISPOSITIVO_IOT CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VETERINARIO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TUTOR CASCADE CONSTRAINTS PURGE';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RACA CASCADE CONSTRAINTS PURGE';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE IDEMPOTENCY_KEY CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_ERRO CASCADE CONSTRAINTS PURGE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIPO_EVENTO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIE CASCADE CONSTRAINTS PURGE';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLINICA CASCADE CONSTRAINTS PURGE';              EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --- 1.4 Sequences KURA (as 29 do V19 + as da Sprint 3, nova e anterior) ---
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDITORIA_COBRANCA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDITORIA';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLINICA';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ESPECIE';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_EVENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RACA';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VETERINARIO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TUTOR';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PET';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INVITE_TUTOR';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVENTO_CLINICO';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICAMENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NOTIFICACAO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DISPOSITIVO_IOT';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LEITURA_TEMP';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTA_TEMP';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TRIAGEM_LUNA';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EXAME';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VACINA';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRESCRICAO';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOCUMENTO';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONSULTA';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOG_ERRO';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INTERACAO_CANAL';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO_CLINICA';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SERVICO_PRECO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COBRANCA';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTA_TUTOR';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONSENTIMENTO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AGENDAMENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IDEMPOTENCY_KEY';    EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT === BLOCO 1: limpeza concluida ===


-- #############################################################################
-- #  BLOCO 2 - SEQUENCES (29)
-- #
-- #  Finalidade: geradores de PK. Criados ANTES das tabelas porque 26 das 30
-- #  tabelas referenciam a sequence na expressao DEFAULT da PK
-- #  (DEFAULT SEQ_X.NEXTVAL - sintaxe Oracle 12c+, confirmada disponivel na
-- #  SD-01 contra o Oracle 19c da FIAP).
-- #
-- #  START WITH 100: convencao herdada das migrations V1/V12 - fica acima do
-- #  maior ID usado pelos seeds de desenvolvimento e pelas linhas ja existentes
-- #  em producao, evitando colisao de PK.
-- #
-- #  TRES SEQUENCES SAO ORFAS DE PROPOSITO - SEQ_CONTA_TUTOR, SEQ_CONSENTIMENTO
-- #  e SEQ_IDEMPOTENCY_KEY: as tabelas correspondentes usam GENERATED BY DEFAULT
-- #  AS IDENTITY (padrao Java-owned) e ninguem puxa dessas sequences. Elas
-- #  existem no banco real (migration V1) e sao mantidas aqui por fidelidade -
-- #  um script que diverge do banco real vale menos na banca que uma incoerencia
-- #  explicada.
-- #
-- #  SEQ_AGENDAMENTO **NAO** e orfa: embora ID_AGENDAMENTO seja IDENTITY no
-- #  banco, a entidade JPA Agendamento.java declara
-- #  @GeneratedValue(strategy = SEQUENCE, generator = "seq_agendamento") e puxa
-- #  desta sequence. As duas coisas coexistem porque GENERATED BY DEFAULT
-- #  (diferente de GENERATED ALWAYS) aceita valor explicito: o Hibernate fornece
-- #  o numero da sequence e o Oracle o respeita.
-- #############################################################################

PROMPT
PROMPT === BLOCO 2: sequences ===

-- --- 2.1 Sequences .NET-owned das tabelas nascidas na V1 (migration V12) ---
CREATE SEQUENCE SEQ_CLINICA        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESPECIE        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_EVENTO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RACA           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VETERINARIO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TUTOR          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PET            START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVITE_TUTOR   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENTO_CLINICO START WITH 100 INCREMENT BY 1;

-- --- 2.2 Sequences .NET-owned das tabelas nascidas na V9 (migration V12) ---
-- SEQ_LEITURA_TEMP / SEQ_ALERTA_TEMP: nomes abreviados vem literalmente das
-- *Configuration.cs do backend .NET - nao "corrigir" para o nome por extenso.
CREATE SEQUENCE SEQ_MEDICAMENTO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICACAO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISPOSITIVO_IOT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEITURA_TEMP    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA_TEMP     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRIAGEM_LUNA    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXAME           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VACINA          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESCRICAO      START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOCUMENTO       START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSULTA        START WITH 100 INCREMENT BY 1;

-- --- 2.3 Sequence de LOG_ERRO (migration V13) ---
CREATE SEQUENCE SEQ_LOG_ERRO       START WITH 100 INCREMENT BY 1;

-- --- 2.4 Sequence de INTERACAO_CANAL (migration V15) ---
CREATE SEQUENCE SEQ_INTERACAO_CANAL START WITH 100 INCREMENT BY 1;

-- --- 2.5 Sequence de USUARIO_CLINICA (migration V17) ---
CREATE SEQUENCE SEQ_USUARIO_CLINICA START WITH 100 INCREMENT BY 1;

-- --- 2.6 Sequences do modulo financeiro (migration V18) ---
CREATE SEQUENCE SEQ_SERVICO_PRECO  START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COBRANCA       START WITH 100 INCREMENT BY 1;

-- --- 2.7 Sequences Java-owned da V1 - SEQ_AGENDAMENTO e usada; as outras 3
--         sao orfas de proposito (ver cabecalho do BLOCO 2) ---
CREATE SEQUENCE SEQ_CONTA_TUTOR     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSENTIMENTO   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AGENDAMENTO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IDEMPOTENCY_KEY START WITH 100 INCREMENT BY 1;

PROMPT === BLOCO 2: 29 sequences criadas ===


-- #############################################################################
-- #  BLOCO 3 - TABELAS (30) - estado consolidado da migration V19
-- #
-- #  Finalidade: criar as 30 tabelas do schema KURA ja no estado FINAL - todas
-- #  as ~75 alteracoes posteriores (ALTER TABLE espalhados por V2..V19) ja
-- #  aplicadas inline. Ordem = topologia de dependencia de FK (5 niveis):
-- #    Nivel 1: CLINICA, ESPECIE, TIPO_EVENTO, MEDICAMENTO, LOG_ERRO, IDEMPOTENCY_KEY
-- #    Nivel 2: RACA, VETERINARIO, TUTOR, DISPOSITIVO_IOT, SERVICO_PRECO
-- #    Nivel 3: PET, INVITE_TUTOR, CONSENTIMENTO, USUARIO_CLINICA,
-- #             LEITURA_TEMPERATURA, INTERACAO_CANAL, NOTIFICACAO
-- #    Nivel 4: TUTOR_PET, CONTA_TUTOR, EVENTO_CLINICO, ALERTA_TEMPERATURA, TRIAGEM_LUNA
-- #    Nivel 5: AGENDAMENTO, CONSULTA, EXAME, VACINA, PRESCRICAO, DOCUMENTO, COBRANCA
-- #
-- #  ESTRATEGIA DE CHAVE PRIMARIA (herdada do banco real, nao uniformizada):
-- #    - 26 tabelas: DEFAULT SEQ_X.NEXTVAL  (padrao .NET-owned, migration V12)
-- #    - 4 tabelas:  GENERATED BY DEFAULT AS IDENTITY  (padrao Java-owned):
-- #                  CONTA_TUTOR, CONSENTIMENTO, IDEMPOTENCY_KEY, AGENDAMENTO
-- #      AGENDAMENTO e IDENTITY no banco E puxa de SEQ_AGENDAMENTO pela entidade
-- #      JPA - estrategia dupla real, nao lixo (ver BLOCO 2).
-- #
-- #  CONVENCAO ADOTADA NA CONSOLIDACAO: toda FK recebe nome explicito
-- #  (FK_<TABELA>_<ALVO>). Nas migrations V9/V15 varias FK nasceram inline sem
-- #  nome (Oracle geraria SYS_Cxxxxx); nomea-las aqui e escolha de legibilidade
-- #  para a banca, nao mudanca de semantica.
-- #
-- #  Booleanos: CHAR(1) 'S'/'N' com CHECK (convencao Oracle do projeto).
-- #  Soft delete: coluna ST_ATIV*/ST_ATIVO - DELETE fisico nunca acontece.
-- #############################################################################

PROMPT
PROMPT === BLOCO 3: tabelas (30) ===

-- ===== NIVEL 1 ==============================================================

-- --- 3.01 CLINICA (.NET owns) - clinicas veterinarias. Raiz do multi-tenant.
--          Consolida: V1 + NM_RAZAO_SOCIAL (V8) + PK->sequence (V12).
CREATE TABLE CLINICA (
    ID_CLINICA      NUMBER(10)    DEFAULT SEQ_CLINICA.NEXTVAL PRIMARY KEY,
    NM_CLINICA      VARCHAR2(120) NOT NULL,
    NR_CNPJ         VARCHAR2(18)  NOT NULL,
    DS_ENDERECO     VARCHAR2(200),
    NM_CIDADE       VARCHAR2(80),
    SG_UF           CHAR(2),
    NR_CEP          VARCHAR2(9),
    DS_TELEFONE     VARCHAR2(20),
    DS_EMAIL        VARCHAR2(120),
    DS_EMAIL_ACESSO VARCHAR2(120),
    DS_SENHA_HASH   VARCHAR2(256),
    DT_CADASTRO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ST_ATIVA        CHAR(1)   DEFAULT 'S' NOT NULL,
    NM_RAZAO_SOCIAL VARCHAR2(150),
    CONSTRAINT UK_CLINICA_CNPJ         UNIQUE (NR_CNPJ),
    CONSTRAINT UK_CLINICA_EMAIL_ACESSO UNIQUE (DS_EMAIL_ACESSO),
    CONSTRAINT CHK_CLINICA_ATIVA       CHECK  (ST_ATIVA IN ('S','N'))
);
COMMENT ON TABLE CLINICA IS 'Clinicas veterinarias - owned pelo .NET. Raiz do isolamento multi-tenant.';

-- --- 3.02 ESPECIE (.NET owns) - especies animais. Consolida: V1 + auditoria (V9) + PK->seq (V12).
CREATE TABLE ESPECIE (
    ID_ESPECIE     NUMBER(10)   DEFAULT SEQ_ESPECIE.NEXTVAL PRIMARY KEY,
    NM_ESPECIE     VARCHAR2(50) NOT NULL,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT UK_ESPECIE_NOME UNIQUE (NM_ESPECIE)
);
COMMENT ON TABLE ESPECIE IS 'Especies animais (Cao, Gato...). Catalogo de baixa mutabilidade.';

-- --- 3.03 TIPO_EVENTO (.NET manages) - catalogo de tipos de evento clinico.
--          Consolida: V1 + CD_TIPO NOT NULL + UK_TIPO_EVENTO_CD + auditoria (V9) + PK->seq (V12).
--          A-3 do mapa: CD_TIPO nasce ja NOT NULL (o backfill da V9 nao existe em schema novo);
--          a carga (BLOCO 7) OBRIGATORIAMENTE preenche CD_TIPO, senao ORA-01400.
CREATE TABLE TIPO_EVENTO (
    ID_TIPO_EVENTO NUMBER(10)    DEFAULT SEQ_TIPO_EVENTO.NEXTVAL PRIMARY KEY,
    NM_TIPO        VARCHAR2(60)  NOT NULL,
    DS_TIPO        VARCHAR2(200),
    ST_ATIVO       CHAR(1) DEFAULT 'S' NOT NULL,
    CD_TIPO        VARCHAR2(20)  NOT NULL,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT UK_TIPO_EVENTO_NM  UNIQUE (NM_TIPO),
    CONSTRAINT UK_TIPO_EVENTO_CD  UNIQUE (CD_TIPO),
    CONSTRAINT CHK_TIPO_EVENTO_ST CHECK  (ST_ATIVO IN ('S','N'))
);
COMMENT ON TABLE TIPO_EVENTO IS 'Catalogo de tipos de evento clinico (CONSULTA, VACINA...). CD_TIPO = chave de negocio.';

-- --- 3.04 MEDICAMENTO (.NET owns) - catalogo para prescricoes. Consolida: V9 + PK->seq (V12).
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO     NUMBER(10)    DEFAULT SEQ_MEDICAMENTO.NEXTVAL PRIMARY KEY,
    NM_MEDICAMENTO     VARCHAR2(200) NOT NULL,
    DS_PRINCIPIO_ATIVO VARCHAR2(500) NOT NULL,
    DS_APRESENTACAO    VARCHAR2(500) NOT NULL,
    DT_CRIACAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP
);
COMMENT ON TABLE MEDICAMENTO IS 'Catalogo de medicamentos para prescricoes - owned pelo .NET.';

-- --- 3.05 LOG_ERRO - log de erros de procedures PL/SQL (requisito FIAP - disciplina BD).
--          Consolida: V13 (nasce no formato final). Sem FK: log de erro nunca deve falhar
--          por violacao referencial. Escrita real em producao: cliente Python da Luna.
CREATE TABLE LOG_ERRO (
    ID_LOG            NUMBER(15)     DEFAULT SEQ_LOG_ERRO.NEXTVAL NOT NULL,
    NM_PROCEDURE      VARCHAR2(120)  NOT NULL,
    NM_USUARIO        VARCHAR2(60)   NOT NULL,
    DT_ERRO           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    NR_CODIGO_ERRO    NUMBER(10)     NOT NULL,
    DS_MENSAGEM_ERRO  VARCHAR2(2000) NOT NULL,
    DS_PARAMETROS     VARCHAR2(2000),
    DS_STACK_TRACE    CLOB,
    CONSTRAINT PK_LOG_ERRO PRIMARY KEY (ID_LOG)
);
COMMENT ON TABLE LOG_ERRO IS 'Log de erros de procedures Oracle (requisito FIAP). Sem FK de proposito. Alimentada pelos handlers de excecao dos objetos da Sprint 3.';

-- --- 3.06 IDEMPOTENCY_KEY (Java owns) - exactly-once para POSTs sensiveis. Consolida: V1
--          (PK IDENTITY - Java-owned, NAO convertida pela V12) + indice de limpeza (V2).
CREATE TABLE IDEMPOTENCY_KEY (
    ID_IDEMPOTENCY     NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DS_KEY             VARCHAR2(64) NOT NULL,
    NM_RESOURCE        VARCHAR2(60) NOT NULL,
    ID_RESOURCE_CRIADO NUMBER(10)   NOT NULL,
    DT_CRIACAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_EXPIRACAO       TIMESTAMP                           NOT NULL,
    CONSTRAINT UK_IDEM_KEY_RESOURCE UNIQUE (DS_KEY, NM_RESOURCE)
);
COMMENT ON TABLE IDEMPOTENCY_KEY IS 'Exactly-once para POSTs sensiveis (CONSENTIMENTO). TTL 24h.';

-- ===== NIVEL 2 ==============================================================

-- --- 3.07 RACA (.NET owns) - racas por especie. Consolida: V1 + auditoria (V9) + PK->seq (V12).
CREATE TABLE RACA (
    ID_RACA          NUMBER(10)   DEFAULT SEQ_RACA.NEXTVAL PRIMARY KEY,
    ID_ESPECIE       NUMBER(10)   NOT NULL,
    NM_RACA          VARCHAR2(80) NOT NULL,
    DS_PREDISPOSICAO VARCHAR2(500),
    DT_CRIACAO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT FK_RACA_ESPECIE FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE)
);
COMMENT ON TABLE RACA IS 'Racas por especie - owned pelo .NET.';

-- --- 3.08 VETERINARIO (.NET owns) - veterinarios da clinica. Consolida: V1 + DT_ATUALIZACAO
--          (V9) + PK->seq (V12) + UK_VET_CLINICA_ID (V19: chave redundante com a PK, criada
--          apenas para ser alvo da FK composta de USUARIO_CLINICA - A-5 do mapa).
CREATE TABLE VETERINARIO (
    ID_VETERINARIO NUMBER(10)    DEFAULT SEQ_VETERINARIO.NEXTVAL PRIMARY KEY,
    ID_CLINICA     NUMBER(10)    NOT NULL,
    NM_VETERINARIO VARCHAR2(150) NOT NULL,
    NR_CRMV        VARCHAR2(20),
    DS_EMAIL       VARCHAR2(150),
    NR_TELEFONE    VARCHAR2(20),
    ST_ATIVO       CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_VET_CLINICA    FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_VET_CRMV       UNIQUE (NR_CRMV),
    CONSTRAINT UK_VET_CLINICA_ID UNIQUE (ID_CLINICA, ID_VETERINARIO),
    CONSTRAINT CHK_VET_ATIVO     CHECK  (ST_ATIVO IN ('S','N'))
);
COMMENT ON TABLE VETERINARIO IS 'Veterinarios vinculados a clinica - owned pelo .NET. UK_VET_CLINICA_ID (V19) e alvo da FK composta que impede vinculo cross-tenant em USUARIO_CLINICA.';

-- --- 3.09 TUTOR (.NET owns) - tutores dos pets. Consolida: V1 + PK->seq (V12). NR_CPF: 11 digitos sem mascara.
CREATE TABLE TUTOR (
    ID_TUTOR             NUMBER(10)    DEFAULT SEQ_TUTOR.NEXTVAL PRIMARY KEY,
    ID_CLINICA           NUMBER(10)    NOT NULL,
    NM_TUTOR             VARCHAR2(200) NOT NULL,
    NR_CPF               VARCHAR2(11)  NOT NULL,
    DS_EMAIL             VARCHAR2(150) NOT NULL,
    DS_TELEFONE          VARCHAR2(20)  NOT NULL,
    DS_WHATSAPP          VARCHAR2(20),
    DT_NASCIMENTO        DATE,
    DS_ENDERECO          VARCHAR2(200),
    NM_CIDADE            VARCHAR2(80),
    SG_UF                CHAR(2),
    NR_CEP               VARCHAR2(9),
    DT_CADASTRO          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO       TIMESTAMP,
    ST_AVISO_PRIVACIDADE CHAR(1) DEFAULT 'N' NOT NULL,
    DT_AVISO_PRIVACIDADE TIMESTAMP,
    DS_VERSAO_AVISO      VARCHAR2(20),
    ST_ATIVO             CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT FK_TUTOR_CLINICA            FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_TUTOR_CPF               UNIQUE (NR_CPF),
    CONSTRAINT UK_TUTOR_EMAIL             UNIQUE (DS_EMAIL),
    CONSTRAINT CHK_TUTOR_AVISO_PRIVACIDADE CHECK (ST_AVISO_PRIVACIDADE IN ('S','N')),
    CONSTRAINT CHK_TUTOR_ATIVO            CHECK (ST_ATIVO IN ('S','N'))
);
COMMENT ON TABLE TUTOR IS 'Tutores dos pets - owned pelo .NET. Java le via @Immutable.';

-- --- 3.10 DISPOSITIVO_IOT (.NET owns) - sensores ESP32 de temperatura. Consolida: V9 + PK->seq (V12).
CREATE TABLE DISPOSITIVO_IOT (
    ID_DISPOSITIVO NUMBER(10)    DEFAULT SEQ_DISPOSITIVO_IOT.NEXTVAL PRIMARY KEY,
    ID_CLINICA     NUMBER(10)    NOT NULL,
    CD_DISPOSITIVO VARCHAR2(20)  NOT NULL,
    DS_DESCRICAO   VARCHAR2(500) NOT NULL,
    DS_LOCALIZACAO VARCHAR2(500) NOT NULL,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_DISPOSITIVO_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_DISPOSITIVO_CD      UNIQUE (CD_DISPOSITIVO)
);
COMMENT ON TABLE DISPOSITIVO_IOT IS 'Sensores IoT de temperatura por clinica - owned pelo .NET.';

-- --- 3.11 SERVICO_PRECO (.NET owns) - catalogo de precos da clinica. Consolida: V18.
--          NAO e fonte de valor de cobranca lancada (ver COBRANCA.VL_COBRADO).
CREATE TABLE SERVICO_PRECO (
    ID_SERVICO_PRECO NUMBER(10)    DEFAULT SEQ_SERVICO_PRECO.NEXTVAL PRIMARY KEY,
    ID_CLINICA       NUMBER(10)    NOT NULL,
    NM_SERVICO       VARCHAR2(200) NOT NULL,
    VL_PRECO         NUMBER(10,2)  NOT NULL,
    ST_ATIVA         CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT FK_SERVICO_PRECO_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT CHK_SERVICO_PRECO_ATIVA  CHECK (ST_ATIVA IN ('S','N')),
    CONSTRAINT CHK_SERVICO_PRECO_VALOR  CHECK (VL_PRECO >= 0)
);
COMMENT ON TABLE SERVICO_PRECO IS 'Catalogo de precos da clinica (ruling D-2). Alterar VL_PRECO nao altera cobranca ja lancada.';

-- ===== NIVEL 3 ==============================================================

-- --- 3.12 PET (.NET owns) - pets vinculados a tutores. Consolida: V1 + PK->seq (V12).
CREATE TABLE PET (
    ID_PET              NUMBER(10)    DEFAULT SEQ_PET.NEXTVAL PRIMARY KEY,
    ID_CLINICA          NUMBER(10)    NOT NULL,
    ID_ESPECIE          NUMBER(10)    NOT NULL,
    ID_RACA             NUMBER(10),
    ID_VETERINARIO_RESP NUMBER(10),
    NM_PET              VARCHAR2(80)  NOT NULL,
    DT_NASCIMENTO       DATE,
    SG_SEXO             CHAR(1),
    NR_PESO_KG          NUMBER(5,2),
    ST_CASTRADO         CHAR(1)  DEFAULT 'N' NOT NULL,
    DS_ALERGIAS         VARCHAR2(500),
    DS_OBSERVACOES      VARCHAR2(1000),
    DT_CADASTRO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SG_PORTE            CHAR(1),
    ST_ATIVO            CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CRIACAO          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_ATUALIZACAO      TIMESTAMP,
    CONSTRAINT FK_PET_CLINICA  FOREIGN KEY (ID_CLINICA)          REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_PET_ESPECIE  FOREIGN KEY (ID_ESPECIE)          REFERENCES ESPECIE(ID_ESPECIE),
    CONSTRAINT FK_PET_RACA     FOREIGN KEY (ID_RACA)             REFERENCES RACA(ID_RACA),
    CONSTRAINT FK_PET_VET_RESP FOREIGN KEY (ID_VETERINARIO_RESP) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CHK_PET_SEXO     CHECK (SG_SEXO IN ('M','F')),
    CONSTRAINT CHK_PET_PORTE    CHECK (SG_PORTE IN ('P','M','G')),
    CONSTRAINT CHK_PET_CASTRADO CHECK (ST_CASTRADO IN ('S','N')),
    CONSTRAINT CHK_PET_ATIVO    CHECK (ST_ATIVO IN ('S','N'))
);
COMMENT ON TABLE PET IS 'Pets vinculados a tutores - owned pelo .NET.';

-- --- 3.13 INVITE_TUTOR (.NET owns) - convites da clinica ao tutor. Consolida: V1 + auditoria (V9) + PK->seq (V12).
CREATE TABLE INVITE_TUTOR (
    ID_INVITE      NUMBER(10)   DEFAULT SEQ_INVITE_TUTOR.NEXTVAL PRIMARY KEY,
    ID_TUTOR       NUMBER(10)   NOT NULL,
    NR_TOKEN       VARCHAR2(36) NOT NULL,
    DT_EXPIRACAO   TIMESTAMP    NOT NULL,
    DS_CANAL       VARCHAR2(20) NOT NULL,
    ST_UTILIZADO   CHAR(1)  DEFAULT 'N' NOT NULL,
    ST_ATIVO       CHAR(1)  DEFAULT 'S' NOT NULL,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_INVITE_TUTOR      FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT UK_INVITE_TOKEN      UNIQUE (NR_TOKEN),
    CONSTRAINT CHK_INVITE_CANAL     CHECK (DS_CANAL IN ('WHATSAPP','EMAIL','SMS')),
    CONSTRAINT CHK_INVITE_UTILIZADO CHECK (ST_UTILIZADO IN ('S','N')),
    CONSTRAINT CHK_INVITE_ATIVO     CHECK (ST_ATIVO IN ('S','N'))
);
COMMENT ON TABLE INVITE_TUTOR IS 'Convites enviados pela clinica ao tutor - gerado pelo .NET, consumido 1x pelo Java.';

-- --- 3.14 CONSENTIMENTO (Java owns) - historico LGPD de consentimentos. Somente INSERT.
--          Consolida: V1 (V4 e no-op de DDL). PK IDENTITY (Java-owned).
CREATE TABLE CONSENTIMENTO (
    ID_CONSENTIMENTO NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_TUTOR         NUMBER(10)    NOT NULL,
    DS_TIPO          VARCHAR2(100) NOT NULL,
    DS_VERSAO_TERMO  VARCHAR2(20)  NOT NULL,
    ST_ACEITO        CHAR(1)       NOT NULL,
    DT_ACEITE        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DS_TEXTO_TERMO   CLOB,
    DS_IP_ACEITE     VARCHAR2(45),
    DT_REVOGACAO     TIMESTAMP,
    DS_IP_REVOGACAO  VARCHAR2(45),
    CONSTRAINT FK_CONSENT_TUTOR   FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT CHK_CONSENT_TIPO   CHECK (DS_TIPO IN ('TELEORIENTACAO','LEMBRETES','DADOS_ANONIMOS','COMPARTILHAR_SEGURADORA','MARKETING')),
    CONSTRAINT CHK_CONSENT_ACEITO CHECK (ST_ACEITO IN ('S','N'))
);
COMMENT ON TABLE CONSENTIMENTO IS 'Historico LGPD de consentimentos - Java owns. Somente INSERT, nunca UPDATE.';

-- --- 3.15 USUARIO_CLINICA (.NET owns) - identidade individual do lado clinico.
--          Consolida: V17 + FK composta (V19: FK_USUARIO_CLINICA_VET passa a ser
--          (ID_CLINICA, ID_VETERINARIO) -> VETERINARIO, impedindo vinculo cross-tenant - A-5).
--          O INSERT..SELECT de conversao D-10 da V17 e migracao de dado em runtime
--          (converte credenciais de CLINICA ja existentes); nao entra aqui - a carga
--          do BLOCO 7 insere USUARIO_CLINICA diretamente.
CREATE TABLE USUARIO_CLINICA (
    ID_USUARIO_CLINICA NUMBER(10)    DEFAULT SEQ_USUARIO_CLINICA.NEXTVAL PRIMARY KEY,
    ID_CLINICA         NUMBER(10)    NOT NULL,
    ID_VETERINARIO     NUMBER(10),
    DS_EMAIL           VARCHAR2(120) NOT NULL,
    DS_SENHA_HASH      VARCHAR2(256) NOT NULL,
    TP_PERFIL          VARCHAR2(20)  NOT NULL,
    ST_ATIVA           CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT FK_USUARIO_CLINICA_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_USUARIO_CLINICA_VET     FOREIGN KEY (ID_CLINICA, ID_VETERINARIO)
                                          REFERENCES VETERINARIO(ID_CLINICA, ID_VETERINARIO),
    CONSTRAINT UK_USUARIO_CLINICA_EMAIL   UNIQUE (ID_CLINICA, DS_EMAIL),
    CONSTRAINT CHK_USUARIO_CLINICA_PERFIL CHECK (TP_PERFIL IN ('GESTOR','VETERINARIO')),
    CONSTRAINT CHK_USUARIO_CLINICA_ATIVA  CHECK (ST_ATIVA IN ('S','N'))
);
COMMENT ON TABLE USUARIO_CLINICA IS 'Identidade individual do lado clinico: uma linha por humano (login proprio + papel). FK com VETERINARIO e composta (V19): banco recusa vet de outra clinica.';

-- --- 3.16 LEITURA_TEMPERATURA (.NET owns) - series temporais IoT. Consolida: V9 + PK->seq (V12).
CREATE TABLE LEITURA_TEMPERATURA (
    ID_LEITURA         NUMBER(10)  DEFAULT SEQ_LEITURA_TEMP.NEXTVAL PRIMARY KEY,
    ID_DISPOSITIVO_IOT NUMBER(10)  NOT NULL,
    VL_TEMPERATURA     NUMBER(5,2) NOT NULL,
    VL_UMIDADE         NUMBER(5,2),
    DT_LEITURA         TIMESTAMP   NOT NULL,
    DT_CRIACAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT FK_LEITURA_DISPOSITIVO FOREIGN KEY (ID_DISPOSITIVO_IOT) REFERENCES DISPOSITIVO_IOT(ID_DISPOSITIVO)
);
COMMENT ON TABLE LEITURA_TEMPERATURA IS 'Series temporais de temperatura/umidade por dispositivo IoT - owned pelo .NET.';

-- --- 3.17 INTERACAO_CANAL (.NET owns) - interacao de canal (WhatsApp/email/SMS) da Luna.
--          Consolida: V15 + ID_CLINICA NULLABLE (V16 - A-4 do mapa: interacao de tutor
--          nao identificado e gravada com clinica nula, para auditoria).
CREATE TABLE INTERACAO_CANAL (
    ID_INTERACAO   NUMBER(10)     DEFAULT SEQ_INTERACAO_CANAL.NEXTVAL PRIMARY KEY,
    ID_CLINICA     NUMBER(10),
    ID_TUTOR       NUMBER(10),
    DS_CANAL       VARCHAR2(20)   NOT NULL,
    DS_DIRECAO     VARCHAR2(20)   NOT NULL,
    DS_CONTEUDO    VARCHAR2(4000) NOT NULL,
    DT_RECEBIMENTO TIMESTAMP      NOT NULL,
    DS_METADADOS   CLOB,
    ST_ATIVA       CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_INTERACAO_CLINICA  FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_INTERACAO_TUTOR    FOREIGN KEY (ID_TUTOR)   REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT CHK_INTERACAO_CANAL   CHECK (DS_CANAL   IN ('WHATSAPP','EMAIL','SMS')),
    CONSTRAINT CHK_INTERACAO_DIRECAO CHECK (DS_DIRECAO IN ('INBOUND','OUTBOUND')),
    CONSTRAINT CHK_INTERACAO_ATIVA   CHECK (ST_ATIVA   IN ('S','N'))
);
COMMENT ON TABLE INTERACAO_CANAL IS 'Interacao de canal registrada pela Luna. ID_CLINICA nullable (V16): NULL = origem nao identificada, gravada para auditoria.';

-- --- 3.18 NOTIFICACAO (.NET owns) - notificacoes internas da clinica. Consolida: V9 + PK->seq (V12).
CREATE TABLE NOTIFICACAO (
    ID_NOTIFICACAO NUMBER(10)    DEFAULT SEQ_NOTIFICACAO.NEXTVAL PRIMARY KEY,
    ID_CLINICA     NUMBER(10)    NOT NULL,
    ID_TUTOR       NUMBER(10),
    ID_VETERINARIO NUMBER(10),
    DS_TITULO      VARCHAR2(200) NOT NULL,
    DS_MENSAGEM    VARCHAR2(500) NOT NULL,
    ST_LIDA        CHAR(1)       DEFAULT 'N' NOT NULL,
    DT_LEITURA     TIMESTAMP,
    DT_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT FK_NOTIFICACAO_CLINICA FOREIGN KEY (ID_CLINICA)     REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_NOTIFICACAO_TUTOR   FOREIGN KEY (ID_TUTOR)       REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_NOTIFICACAO_VET     FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CHK_NOTIF_LIDA CHECK (ST_LIDA IN ('S','N'))
);
COMMENT ON TABLE NOTIFICACAO IS 'Notificacoes internas da clinica (tutor e/ou veterinario) - owned pelo .NET.';

-- ===== NIVEL 4 ==============================================================

-- --- 3.19 TUTOR_PET (.NET owns) - vinculo N:N tutor/pet. Consolida: V1 (PK composta, sem coluna gerada).
CREATE TABLE TUTOR_PET (
    ID_TUTOR     NUMBER(10)   NOT NULL,
    ID_PET       NUMBER(10)   NOT NULL,
    DS_VINCULO   VARCHAR2(40) DEFAULT 'PROPRIETARIO' NOT NULL,
    DT_VINCULO   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ST_PRINCIPAL CHAR(1)      DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_TUTOR_PET     PRIMARY KEY (ID_TUTOR, ID_PET),
    CONSTRAINT FK_TP_TUTOR      FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_TP_PET        FOREIGN KEY (ID_PET)   REFERENCES PET(ID_PET),
    CONSTRAINT CHK_TP_PRINCIPAL CHECK (ST_PRINCIPAL IN ('S','N'))
);
COMMENT ON TABLE TUTOR_PET IS 'Vinculo N:N tutor/pet. ST_PRINCIPAL=S indica quem recebe notificacoes.';

-- --- 3.20 CONTA_TUTOR (Java owns) - credenciais de acesso do tutor. Consolida: V1 +
--          UK_CONTA_INVITE_USED (V3) + push token DS_PUSH_TOKEN/DS_PLATAFORMA_PUSH + CHK (V7).
--          PK IDENTITY (Java-owned).
CREATE TABLE CONTA_TUTOR (
    ID_CONTA              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_TUTOR              NUMBER(10)    NOT NULL,
    DS_EMAIL_LOGIN        VARCHAR2(200) NOT NULL,
    DS_SENHA_HASH         VARCHAR2(256) NOT NULL,
    DS_REFRESH_TOKEN_HASH VARCHAR2(256),
    DT_REFRESH_EXPIRA     TIMESTAMP,
    ID_INVITE_USADO       NUMBER(10),
    DT_CRIACAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ULTIMO_LOGIN       TIMESTAMP,
    NR_TENTATIVAS_LOGIN   NUMBER(2) DEFAULT 0 NOT NULL,
    DT_BLOQUEIO           TIMESTAMP,
    ST_ATIVA             CHAR(1) DEFAULT 'S' NOT NULL,
    ST_EMAIL_VERIFICADO  CHAR(1) DEFAULT 'N' NOT NULL,
    DS_TOKEN_RESET        VARCHAR2(256),
    DT_TOKEN_EXPIRA       TIMESTAMP,
    DS_PUSH_TOKEN         VARCHAR2(512),
    DS_PLATAFORMA_PUSH    VARCHAR2(10),
    CONSTRAINT UK_CONTA_TUTOR_EMAIL UNIQUE (DS_EMAIL_LOGIN),
    CONSTRAINT UK_CONTA_TUTOR_TUTOR UNIQUE (ID_TUTOR),
    CONSTRAINT UK_CONTA_INVITE_USED UNIQUE (ID_INVITE_USADO),
    CONSTRAINT FK_CONTA_TUTOR_TUTOR FOREIGN KEY (ID_TUTOR)        REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_CONTA_INVITE      FOREIGN KEY (ID_INVITE_USADO) REFERENCES INVITE_TUTOR(ID_INVITE),
    CONSTRAINT CHK_CONTA_ATIVA      CHECK (ST_ATIVA IN ('S','N')),
    CONSTRAINT CHK_CONTA_EMAIL_VER  CHECK (ST_EMAIL_VERIFICADO IN ('S','N')),
    CONSTRAINT CHK_PLATAFORMA_PUSH  CHECK (DS_PLATAFORMA_PUSH IN ('ios','android') OR DS_PLATAFORMA_PUSH IS NULL)
);
COMMENT ON TABLE CONTA_TUTOR IS 'Credenciais de acesso do tutor - Java owns. Criada no fluxo register-invite.';

-- --- 3.21 EVENTO_CLINICO (.NET owns) - evento clinico (era stub na V1). Consolida:
--          V1 (stub) + 6 colunas + 3 FK (V9) + 5 CLOB SOAP + ST_SOAP_CONFIRMADO + CHK (V11) + PK->seq (V12).
CREATE TABLE EVENTO_CLINICO (
    ID_EVENTO          NUMBER(10) DEFAULT SEQ_EVENTO_CLINICO.NEXTVAL PRIMARY KEY,
    ID_PET             NUMBER(10),
    DS_DESCRICAO       VARCHAR2(500),
    DT_EVENTO          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CLINICA         NUMBER(10)     NOT NULL,
    ID_VETERINARIO     NUMBER(10)     NOT NULL,
    ID_TIPO_EVENTO     NUMBER(10)     NOT NULL,
    DS_OBSERVACAO      VARCHAR2(1000) NOT NULL,
    DT_CRIACAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    DS_TRANSCRICAO     CLOB,
    DS_SOAP_S          CLOB,
    DS_SOAP_O          CLOB,
    DS_SOAP_A          CLOB,
    DS_SOAP_P          CLOB,
    ST_SOAP_CONFIRMADO CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_EVENTO_PET     FOREIGN KEY (ID_PET)         REFERENCES PET(ID_PET),
    CONSTRAINT FK_EVENTO_CLINICA FOREIGN KEY (ID_CLINICA)     REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_EVENTO_VET     FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT FK_EVENTO_TIPO    FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPO_EVENTO(ID_TIPO_EVENTO),
    CONSTRAINT CHK_EVENTO_SOAP_CONFIRMADO CHECK (ST_SOAP_CONFIRMADO IN ('S','N'))
);
COMMENT ON TABLE EVENTO_CLINICO IS 'Evento clinico - owned pelo .NET. Entidade completa desde a V9 (era stub na V1). SOAP draft revisavel pelo vet (V11).';

-- --- 3.22 ALERTA_TEMPERATURA (.NET owns) - alertas de leitura fora do limite. Consolida: V9 + PK->seq (V12).
CREATE TABLE ALERTA_TEMPERATURA (
    ID_ALERTA              NUMBER(10)    DEFAULT SEQ_ALERTA_TEMP.NEXTVAL PRIMARY KEY,
    ID_LEITURA_TEMPERATURA NUMBER(10)    NOT NULL,
    DS_TIPO_ALERTA         VARCHAR2(50)  NOT NULL,
    VL_LIMITE              NUMBER(5,2)   NOT NULL,
    DS_MENSAGEM            VARCHAR2(500) NOT NULL,
    ST_RESOLVIDO           CHAR(1)       DEFAULT 'N' NOT NULL,
    DT_CRIACAO             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO         TIMESTAMP,
    CONSTRAINT FK_ALERTA_LEITURA    FOREIGN KEY (ID_LEITURA_TEMPERATURA) REFERENCES LEITURA_TEMPERATURA(ID_LEITURA),
    CONSTRAINT CHK_ALERTA_RESOLVIDO CHECK (ST_RESOLVIDO IN ('S','N'))
);
COMMENT ON TABLE ALERTA_TEMPERATURA IS 'Alertas disparados quando uma leitura IoT ultrapassa o limite - owned pelo .NET.';

-- --- 3.23 TRIAGEM_LUNA (.NET owns) - resultado de triagens de IA da Luna. Consolida:
--          V9 + PK->seq (V12) + ID_INTERACAO FK -> INTERACAO_CANAL (V15).
--          DS_NIVEL_URGENCIA e o destino da FN_CALCULAR_SCORE_URGENCIA (SD-06).
CREATE TABLE TRIAGEM_LUNA (
    ID_TRIAGEM         NUMBER(10)     DEFAULT SEQ_TRIAGEM_LUNA.NEXTVAL PRIMARY KEY,
    ID_CLINICA         NUMBER(10)     NOT NULL,
    ID_TUTOR           NUMBER(10),
    ID_PET             NUMBER(10),
    DS_NIVEL_URGENCIA  VARCHAR2(20)   NOT NULL,
    DS_DESCRICAO       VARCHAR2(2000) NOT NULL,
    ST_ENCAMINHADO_VET CHAR(1)        DEFAULT 'N' NOT NULL,
    DT_TRIAGEM         TIMESTAMP      NOT NULL,
    ST_ATIVA           CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    ID_INTERACAO       NUMBER(10),
    CONSTRAINT FK_TRIAGEM_CLINICA      FOREIGN KEY (ID_CLINICA)   REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_TRIAGEM_TUTOR        FOREIGN KEY (ID_TUTOR)     REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_TRIAGEM_PET          FOREIGN KEY (ID_PET)       REFERENCES PET(ID_PET),
    CONSTRAINT FK_TRIAGEM_INTERACAO    FOREIGN KEY (ID_INTERACAO) REFERENCES INTERACAO_CANAL(ID_INTERACAO),
    CONSTRAINT CHK_TRIAGEM_ENCAMINHADO CHECK (ST_ENCAMINHADO_VET IN ('S','N')),
    CONSTRAINT CHK_TRIAGEM_ATIVA       CHECK (ST_ATIVA IN ('S','N'))
);
COMMENT ON TABLE TRIAGEM_LUNA IS 'Resultado de triagens de IA registradas pela Luna. DS_NIVEL_URGENCIA e o destino da FN_CALCULAR_SCORE_URGENCIA (Sprint 3).';

-- ===== NIVEL 5 ==============================================================

-- --- 3.24 AGENDAMENTO (Java + .NET shared-write) - agendamentos. Consolida: V1 (PK IDENTITY) +
--          8 colunas + FK_AGEND_EVENTO (V5) + 5 colunas teleconsulta + CHK_AGENDA_TELECONSULTA (V10).
--          Optimistic locking via NR_VERSION (@Version) - sincroniza Java e .NET via HTTP 409.
CREATE TABLE AGENDAMENTO (
    ID_AGENDAMENTO     NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_CLINICA         NUMBER(10)   NOT NULL,
    ID_TUTOR           NUMBER(10),
    ID_PET             NUMBER(10),
    ID_VETERINARIO     NUMBER(10),
    DT_AGENDAMENTO     TIMESTAMP    NOT NULL,
    NR_DURACAO_MINUTOS NUMBER(4)    DEFAULT 30,
    DS_TIPO            VARCHAR2(30),
    ST_STATUS          VARCHAR2(20) DEFAULT 'AGENDADO' NOT NULL,
    DS_ORIGEM          VARCHAR2(20) DEFAULT 'PORTAL'   NOT NULL,
    NR_VERSION         NUMBER(10)   DEFAULT 0          NOT NULL,
    NM_PACIENTE        VARCHAR2(200),
    DS_SERVICO         VARCHAR2(200),
    DS_OBSERVACOES     VARCHAR2(1000),
    DT_CRIACAO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_CONFIRMACAO     TIMESTAMP,
    DT_CANCELAMENTO    TIMESTAMP,
    DS_MOTIVO_CANCEL   VARCHAR2(500),
    ID_EVENTO_GERADO   NUMBER(10),
    DS_SALA_URL        VARCHAR2(512),
    DS_PROVEDOR_VIDEO  VARCHAR2(30),
    ST_TELECONSULTA    CHAR(1) DEFAULT 'N' NOT NULL,
    DT_INICIO_SESSAO   TIMESTAMP,
    DT_FIM_SESSAO      TIMESTAMP,
    CONSTRAINT FK_AGEND_CLINICA FOREIGN KEY (ID_CLINICA)       REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_AGEND_TUTOR   FOREIGN KEY (ID_TUTOR)         REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_AGEND_PET     FOREIGN KEY (ID_PET)           REFERENCES PET(ID_PET),
    CONSTRAINT FK_AGEND_VET     FOREIGN KEY (ID_VETERINARIO)   REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT FK_AGEND_EVENTO  FOREIGN KEY (ID_EVENTO_GERADO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT CHK_AGEND_STATUS CHECK (ST_STATUS IN ('INTENCAO','AGENDADO','CONFIRMADO','REALIZADO','CANCELADO','NAO_COMPARECEU')),
    CONSTRAINT CHK_AGENDA_TELECONSULTA CHECK (ST_TELECONSULTA IN ('S','N'))
);
COMMENT ON TABLE AGENDAMENTO IS 'Shared-write: Java cria/edita/cancela; .NET atualiza ST_STATUS. NR_VERSION = optimistic locking (409).';

-- --- 3.25 CONSULTA (.NET owns) - detalhe de consulta (1:1 com EVENTO_CLINICO). Consolida:
--          V9 + UK_CONSULTA_EVENTO_CLINICO + PK->seq (V12).
CREATE TABLE CONSULTA (
    ID_CONSULTA       NUMBER(10)     DEFAULT SEQ_CONSULTA.NEXTVAL PRIMARY KEY,
    ID_EVENTO_CLINICO NUMBER(10)     NOT NULL,
    DS_MOTIVO         VARCHAR2(200)  NOT NULL,
    DS_ANAMNESE       VARCHAR2(2000),
    DS_EXAME_FISICO   VARCHAR2(2000),
    DS_DIAGNOSTICO    VARCHAR2(1000),
    DT_CONSULTA       TIMESTAMP      NOT NULL,
    ST_ATIVA          CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT FK_CONSULTA_EVENTO         FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT UK_CONSULTA_EVENTO_CLINICO UNIQUE (ID_EVENTO_CLINICO),
    CONSTRAINT CHK_CONSULTA_ATIVA         CHECK (ST_ATIVA IN ('S','N'))
);
COMMENT ON TABLE CONSULTA IS 'Detalhe de consulta (1:1 com EVENTO_CLINICO) - owned pelo .NET.';

-- --- 3.26 EXAME (.NET owns) - resultado de exame vinculado a evento clinico. Consolida: V9 + PK->seq (V12).
CREATE TABLE EXAME (
    ID_EXAME          NUMBER(10)     DEFAULT SEQ_EXAME.NEXTVAL PRIMARY KEY,
    ID_EVENTO_CLINICO NUMBER(10)     NOT NULL,
    NM_EXAME          VARCHAR2(200)  NOT NULL,
    DS_RESULTADO      VARCHAR2(1000) NOT NULL,
    DT_REALIZACAO     TIMESTAMP      NOT NULL,
    DT_CRIACAO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT FK_EXAME_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);
COMMENT ON TABLE EXAME IS 'Resultado de exame vinculado a um evento clinico - owned pelo .NET.';

-- --- 3.27 VACINA (.NET owns) - aplicacao de vacina vinculada a evento clinico. Consolida: V9 + PK->seq (V12).
CREATE TABLE VACINA (
    ID_VACINA         NUMBER(10)    DEFAULT SEQ_VACINA.NEXTVAL PRIMARY KEY,
    ID_EVENTO_CLINICO NUMBER(10)    NOT NULL,
    NM_VACINA         VARCHAR2(200) NOT NULL,
    NR_LOTE           VARCHAR2(50)  NOT NULL,
    DS_FABRICANTE     VARCHAR2(200) NOT NULL,
    DT_PROXIMA_DOSE   TIMESTAMP,
    DT_CRIACAO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT FK_VACINA_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);
COMMENT ON TABLE VACINA IS 'Aplicacao de vacina vinculada a um evento clinico - owned pelo .NET.';

-- --- 3.28 PRESCRICAO (.NET owns) - prescricao de medicamento. Consolida: V9 + PK->seq (V12).
CREATE TABLE PRESCRICAO (
    ID_PRESCRICAO     NUMBER(10)    DEFAULT SEQ_PRESCRICAO.NEXTVAL PRIMARY KEY,
    ID_EVENTO_CLINICO NUMBER(10)    NOT NULL,
    ID_MEDICAMENTO    NUMBER(10)    NOT NULL,
    DS_POSOLOGIA      VARCHAR2(500) NOT NULL,
    NR_DURACAO_DIAS   NUMBER(10)    NOT NULL,
    DT_CRIACAO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT FK_PRESCRICAO_EVENTO      FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT FK_PRESCRICAO_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO)    REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);
COMMENT ON TABLE PRESCRICAO IS 'Prescricao de medicamento vinculada a um evento clinico - owned pelo .NET.';

-- --- 3.29 DOCUMENTO (.NET owns) - metadados de documento vinculado a evento clinico. Consolida: V9 + PK->seq (V12).
CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO      NUMBER(10)    DEFAULT SEQ_DOCUMENTO.NEXTVAL PRIMARY KEY,
    ID_EVENTO_CLINICO NUMBER(10)    NOT NULL,
    NM_ARQUIVO        VARCHAR2(200) NOT NULL,
    DS_TIPO_MIME      VARCHAR2(100) NOT NULL,
    DS_CAMINHO        VARCHAR2(500) NOT NULL,
    NR_TAMANHO_BYTES  NUMBER(19)    NOT NULL,
    DT_CRIACAO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT FK_DOCUMENTO_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);
COMMENT ON TABLE DOCUMENTO IS 'Metadados de documento (PDF, imagem) vinculado a um evento clinico - owned pelo .NET.';

-- --- 3.30 COBRANCA (.NET owns) - lancamento financeiro. Consolida: V18.
--          *** TABELA DE FATOS DA SPRINT 3 *** - os 5 objetos PL/SQL operam sobre ela:
--          ID_CLINICA e DS_FORMA_PAGAMENTO = categoricas; VL_COBRADO NUMBER(10,2) = numerica.
--          VL_COBRADO e COPIA do valor no momento do lancamento (nao lido por FK): mudar
--          SERVICO_PRECO.VL_PRECO nao reescreve historico. ID_SERVICO_PRECO e DS_FORMA_PAGAMENTO
--          sao nullable de proposito.
CREATE TABLE COBRANCA (
    ID_COBRANCA        NUMBER(10)   DEFAULT SEQ_COBRANCA.NEXTVAL PRIMARY KEY,
    ID_EVENTO_CLINICO  NUMBER(10)   NOT NULL,
    ID_CLINICA         NUMBER(10)   NOT NULL,
    ID_SERVICO_PRECO   NUMBER(10),
    VL_COBRADO         NUMBER(10,2) NOT NULL,
    DS_FORMA_PAGAMENTO VARCHAR2(30),
    DT_COBRANCA        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ST_ATIVA           CHAR(1)      DEFAULT 'S' NOT NULL,
    DT_CRIACAO         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT FK_COBRANCA_EVENTO  FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT FK_COBRANCA_CLINICA FOREIGN KEY (ID_CLINICA)        REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_COBRANCA_SERVICO FOREIGN KEY (ID_SERVICO_PRECO)  REFERENCES SERVICO_PRECO(ID_SERVICO_PRECO),
    CONSTRAINT CHK_COBRANCA_ATIVA  CHECK (ST_ATIVA IN ('S','N')),
    CONSTRAINT CHK_COBRANCA_VALOR  CHECK (VL_COBRADO >= 0)
);
COMMENT ON TABLE COBRANCA IS 'Lancamento financeiro (ruling D-3). *** Tabela de fatos da Sprint 3 ***. VL_COBRADO e copia do valor no lancamento - nao reescreve historico ao mudar SERVICO_PRECO.';

PROMPT === BLOCO 3: 30 tabelas criadas ===


-- #############################################################################
-- #  BLOCO 4 - INDICES (13)
-- #
-- #  Finalidade: indices de consulta frequente declarados explicitamente pelas
-- #  migrations (alem dos indices que o Oracle cria sozinho para PK e UNIQUE).
-- #
-- #  NOTA DE CONTAGEM: o mapa de consolidacao listava 10; a releitura das
-- #  migrations na SD-02 achou 13 - o mapa nao contava IDX_AGEND_EVENTO (V5) nem
-- #  os 2 indices de COBRANCA (V18). Numero correto: 13.
-- #############################################################################

PROMPT
PROMPT === BLOCO 4: indices ===

-- V1 - consultas frequentes de agenda, consentimento e pet
CREATE INDEX IDX_AGEND_TUTOR   ON AGENDAMENTO(ID_TUTOR);
CREATE INDEX IDX_AGEND_PET     ON AGENDAMENTO(ID_PET);
CREATE INDEX IDX_AGEND_DT      ON AGENDAMENTO(DT_AGENDAMENTO);
CREATE INDEX IDX_CONSENT_TUTOR ON CONSENTIMENTO(ID_TUTOR, DS_TIPO);
CREATE INDEX IDX_PET_ESPECIE   ON PET(ID_ESPECIE);
CREATE INDEX IDX_PET_RACA      ON PET(ID_RACA);

-- V2 - otimiza o DELETE em lote de limpeza da IDEMPOTENCY_KEY
CREATE INDEX IDX_IDEMPOT_CRIACAO ON IDEMPOTENCY_KEY(DT_CRIACAO);

-- V3 - busca de invite por token/estado
CREATE INDEX IDX_INVITE_TOKEN_ATIVO ON INVITE_TUTOR(NR_TOKEN, ST_UTILIZADO, ST_ATIVO);

-- V5 - FK filha sem indice vira varredura na checagem de lock; precedente para IDX_COBRANCA_EVENTO
CREATE INDEX IDX_AGEND_EVENTO ON AGENDAMENTO(ID_EVENTO_GERADO);

-- V13 - consulta de LOG_ERRO por data (mais recentes) e por procedure
CREATE INDEX IDX_LOG_DATA      ON LOG_ERRO(DT_ERRO DESC);
CREATE INDEX IDX_LOG_PROCEDURE ON LOG_ERRO(NM_PROCEDURE);

-- V18 - caminho quente do modulo financeiro: "por clinica e por periodo" (ID_CLINICA
--       igualdade primeiro, DT_COBRANCA faixa depois) + leitura "cobrancas deste atendimento"
CREATE INDEX IDX_COBRANCA_CLINICA_DATA ON COBRANCA(ID_CLINICA, DT_COBRANCA);
CREATE INDEX IDX_COBRANCA_EVENTO       ON COBRANCA(ID_EVENTO_CLINICO);

PROMPT === BLOCO 4: 13 indices criados ===


-- #############################################################################
-- #  BLOCO 5 - VIEWS (2)
-- #
-- #  Finalidade: leitura cruzada entre servicos. Usadas pelo backend Java.
-- #  Versao consolidada = a da migration V6 (que SUBSTITUIU a versao original da
-- #  V1: aliases de coluna renomeados para os nomes canonicos das entidades Java
-- #  - ID_EVENTO em vez de ID_AGENDAMENTO, DT_EVENTO em vez de DT_AGENDAMENTO,
-- #  NM_VACINA e DT_PROXIMA_DOSE em VW_VACINAS_VENCENDO).
-- #############################################################################

PROMPT
PROMPT === BLOCO 5: views ===

CREATE OR REPLACE VIEW VW_TIMELINE_PET AS
SELECT
    a.ID_PET,
    a.ID_AGENDAMENTO  AS ID_EVENTO,
    p.NM_PET,
    a.DT_AGENDAMENTO  AS DT_EVENTO,
    a.DS_TIPO         AS DS_TIPO_EVENTO,
    a.ST_STATUS,
    a.ID_CLINICA,
    c.NM_CLINICA
FROM   AGENDAMENTO a
JOIN   PET          p ON p.ID_PET     = a.ID_PET
JOIN   CLINICA      c ON c.ID_CLINICA = a.ID_CLINICA
WHERE  a.ID_PET IS NOT NULL;

COMMENT ON TABLE VW_TIMELINE_PET IS 'Linha do tempo de atendimentos por pet - lida pelo Java (TimelineService).';

CREATE OR REPLACE VIEW VW_VACINAS_VENCENDO AS
SELECT
    p.ID_PET,
    p.NM_PET,
    a.ID_TUTOR,
    a.DS_TIPO         AS NM_VACINA,
    a.DT_AGENDAMENTO  AS DT_PROXIMA_DOSE,
    a.ID_CLINICA,
    c.NM_CLINICA
FROM   AGENDAMENTO a
JOIN   PET         p ON p.ID_PET     = a.ID_PET
JOIN   CLINICA     c ON c.ID_CLINICA = a.ID_CLINICA
WHERE  a.DS_TIPO   = 'VACINA'
  AND  a.ST_STATUS NOT IN ('CANCELADO','REALIZADO')
  AND  a.DT_AGENDAMENTO >= CURRENT_TIMESTAMP
  AND  a.DT_AGENDAMENTO <= CURRENT_TIMESTAMP + INTERVAL '30' DAY;

COMMENT ON TABLE VW_VACINAS_VENCENDO IS 'Vacinas agendadas nos proximos 30 dias - alertas preventivos.';

PROMPT === BLOCO 5: 2 views criadas ===


-- #############################################################################
-- #  BLOCO 6 - TABELA DE AUDITORIA DA SPRINT 3 (AUDITORIA_COBRANCA)
-- #
-- #  Finalidade: trilha de auditoria DML da tabela COBRANCA, exigida pela
-- #  rubrica da Sprint 3 (30 pts). Objeto ACADEMICO - nao existe nas migrations
-- #  Flyway e nao vai para o produto (uma trigger PL/SQL nao roda no H2 do
-- #  profile 'dev'). O numero de migration V20 NAO e queimado por este arquivo.
-- #
-- #  Os 5 campos exigidos pela rubrica: NM_USUARIO (quem), DS_OPERACAO (o que:
-- #  INSERT/UPDATE/DELETE), DT_OPERACAO (quando), DS_VALORES_OLD (:OLD),
-- #  DS_VALORES_NEW (:NEW). Preenchida EXCLUSIVAMENTE pela TRG_AUDITORIA_COBRANCA
-- #  (BLOCO 10) - ver comentario do BLOCO 7 sobre carga.
-- #
-- #  SEM FK para COBRANCA de proposito: auditoria de DELETE com FK ativa seria
-- #  autocontraditoria (a linha auditada acabou de deixar de existir). Mesmo
-- #  raciocinio ja aplicado a LOG_ERRO na migration V13.
-- #############################################################################

PROMPT
PROMPT === BLOCO 6: tabela de auditoria ===

CREATE SEQUENCE SEQ_AUDITORIA_COBRANCA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AUDITORIA_COBRANCA (
    ID_AUDITORIA   NUMBER(15)   DEFAULT SEQ_AUDITORIA_COBRANCA.NEXTVAL PRIMARY KEY,
    NM_USUARIO     VARCHAR2(60)  NOT NULL,   -- USER do banco (rubrica: nome do usuario)
    DS_OPERACAO    VARCHAR2(10)  NOT NULL,   -- INSERT | UPDATE | DELETE
    DT_OPERACAO    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ID_COBRANCA    NUMBER(10),               -- PK do registro afetado (sem FK - ver cabecalho)
    DS_VALORES_OLD VARCHAR2(4000),           -- :OLD serializado por FN_COBRANCA_TO_JSON
    DS_VALORES_NEW VARCHAR2(4000),           -- :NEW serializado por FN_COBRANCA_TO_JSON
    CONSTRAINT CHK_AUDITORIA_COBRANCA_OP CHECK (DS_OPERACAO IN ('INSERT','UPDATE','DELETE'))
);

CREATE INDEX IDX_AUDITORIA_COB_DATA ON AUDITORIA_COBRANCA(DT_OPERACAO DESC);
CREATE INDEX IDX_AUDITORIA_COB_REG  ON AUDITORIA_COBRANCA(ID_COBRANCA);

COMMENT ON TABLE  AUDITORIA_COBRANCA                IS 'Trilha de auditoria DML de COBRANCA (Sprint 3 - FIAP). Gravada pela TRG_AUDITORIA_COBRANCA. Objeto academico - nao vai para o Flyway.';
COMMENT ON COLUMN AUDITORIA_COBRANCA.NM_USUARIO     IS 'Usuario Oracle que executou a operacao (funcao USER).';
COMMENT ON COLUMN AUDITORIA_COBRANCA.DS_OPERACAO    IS 'Tipo do DML capturado: INSERT, UPDATE ou DELETE.';
COMMENT ON COLUMN AUDITORIA_COBRANCA.DS_VALORES_OLD IS 'Snapshot :OLD serializado em JSON - nulo em INSERT.';
COMMENT ON COLUMN AUDITORIA_COBRANCA.DS_VALORES_NEW IS 'Snapshot :NEW serializado em JSON - nulo em DELETE.';

PROMPT === BLOCO 6: AUDITORIA_COBRANCA criada ===
PROMPT
PROMPT === FIM DA ESTRUTURA (BLOCOS 0-6). Blocos 7-11 nas tasks SD-03..SD-08. ===
