-- #############################################################################
-- #  2TDSX_2024_CodigoSql_Integrantes.sql
-- #  KURA - Sistema de Gestao de Continuidade Veterinaria (Clyvo Vet)
-- #  FIAP Challenge 2026 - Sprint 3
-- #  Disciplina: Mastering Relational and Non-Relational Database
-- #############################################################################
-- #
-- #  INTEGRANTES (ordem alfabetica pelo primeiro nome):
-- #    - Clayton Alves ................ RM562285
-- #    - Felipe Ferrete Soares Lemes .. RM562999
-- #    - Guilherme Sola ............... RM563674
-- #    - Gustavo Bosak ............... RM566315
-- #    - Nikolas Brisola ............. RM564371
-- #  NOTA: a rubrica exige NOMES COMPLETOS. Apenas Felipe tem nome completo
-- #  registrado em arquivo; os outros 4 aparecem como nome + sobrenome. Os nomes
-- #  completos e o "X"/"2024" do nome deste arquivo dependem de confirmacao
-- #  humana (professor + integrantes) - ver o PDF de entrega (SD-09).
-- #
-- #  Turma:      2TDSX  (2o ano, Analise e Desenvolvimento de Sistemas)
-- #  Data:       2026-09-08
-- #  Banco:      Oracle Database 19c Enterprise Edition (parceria FIAP x Oracle)
-- #
-- #############################################################################
-- #  ESCOPO DESTE ARQUIVO
-- #
-- #  Este arquivo e o SCHEMA CONSOLIDADO do sistema KURA no estado da migration
-- #  Flyway V19 - 30 tabelas - MAIS os 5 objetos PL/SQL e a tabela de auditoria
-- #  exigidos pela Sprint 3.
-- #
-- #  O schema real do KURA e mantido por 19 migrations Flyway no repositorio
-- #  backend-tutor-java (db/migration + db/migration-oracle). Este arquivo e a
-- #  CONSOLIDACAO dessas 19 migrations num unico script executavel: cada tabela
-- #  ja nasce no estado final, com todas as ~75 alteracoes posteriores (ALTER
-- #  TABLE) ja aplicadas. Ele reflete o banco real, com as incoerencias herdadas
-- #  (sequences orfas, estrategia dupla de PK em AGENDAMENTO) - um script "mais
-- #  limpo" que o banco real seria um script que nao corresponde ao sistema.
-- #
-- #  AMBIENTE DE EXECUCAO: schema de aluno no Oracle FIAP. Esse schema e
-- #  COMPARTILHADO por varias disciplinas de banco (ha ~70 tabelas de outros
-- #  trabalhos no mesmo schema). Por isso o BLOCO 1 (limpeza) derruba SOMENTE os
-- #  objetos do KURA, por nome - nunca um "DROP" generico. E por isso a
-- #  conferencia de contagem e feita por NOME (WHERE table_name IN (...)), nao
-- #  por SELECT COUNT(*) FROM user_tables.
-- #
-- #  ESTRUTURA:
-- #    BLOCO 0  - Cabecalho e configuracao de sessao (este bloco)
-- #    BLOCO 1  - Limpeza idempotente (DROP dos objetos KURA, por nome)
-- #    BLOCO 2  - 29 sequences
-- #    BLOCO 3  - 30 tabelas (estado V19), em ordem de dependencia de FK
-- #    BLOCO 4  - Indices
-- #    BLOCO 5  - 2 views
-- #    BLOCO 6  - Tabela de auditoria da Sprint 3 (AUDITORIA_COBRANCA)
-- #    BLOCO 7  - Carga de dados (>= 5 registros por tabela) .......... [SD-03]
-- #    BLOCO 8  - Funcoes: FN_COBRANCA_TO_JSON, FN_CALCULAR_SCORE_URGENCIA [SD-04/06]
-- #    BLOCO 9  - Procedimentos: PRC_LISTAR_COBRANCAS_JSON, PRC_RELATORIO_COBRANCAS [SD-04/05]
-- #    BLOCO 10 - Trigger: TRG_AUDITORIA_COBRANCA .................... [SD-07]
-- #    BLOCO 11 - Bloco de demonstracao (caminho feliz + excecoes) ... [SD-08]
-- #
-- #  NENHUMA credencial, host, senha ou connection string neste arquivo.
-- #  Todos os dados de carga (BLOCO 7) sao ficticios e declarados como tais.
-- #############################################################################

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET LINESIZE 200
SET PAGESIZE 1000
WHENEVER SQLERROR CONTINUE


-- #############################################################################
-- #  BLOCO 1 - LIMPEZA IDEMPOTENTE (namespaced)
-- #
-- #  Finalidade: tornar o script re-executavel. Derruba, POR NOME, apenas os
-- #  objetos do KURA e da tentativa anterior de Sprint 3 - nunca objetos de
-- #  outras disciplinas presentes no mesmo schema de aluno.
-- #
-- #  Cada DROP e isolado num bloco PL/SQL com "EXCEPTION WHEN OTHERS THEN NULL":
-- #  se o objeto nao existe (primeira execucao, ou schema limpo), o erro
-- #  (ORA-00942 / ORA-02289 / ORA-04043 / ORA-04080) e engolido e o script
-- #  segue. TABLE usa CASCADE CONSTRAINTS para dispensar a ordem inversa de FK.
-- #
-- #  Objetos de outras disciplinas que porventura referenciem tabelas KURA
-- #  (nao ha nenhum conhecido) ou objetos PL/SQL da Sprint 1/2 do proprio KURA
-- #  (PRC_INSERT_*, REQ 1-4) podem ficar INVALID apos este bloco - isso e
-- #  esperado e nao e erro: recompilam sozinhos ou ao rodar o schema da Sprint
-- #  anterior. A conferencia de aceite da Sprint 3 olha so os objetos deste
-- #  arquivo.
-- #############################################################################

PROMPT
PROMPT === BLOCO 1: limpeza dos objetos KURA (idempotente) ===

-- --- 1.1 Trigger e objetos PL/SQL da Sprint 3 (nova e a tentativa anterior) ---
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDITORIA_COBRANCA';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_AGENDAMENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_LISTAR_COBRANCAS_JSON';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_RELATORIO_COBRANCAS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_EXPORTA_PETS_JSON';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_TOTALIZA_AGENDA_MINUTOS';EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_COBRANCA_TO_JSON';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CALCULAR_SCORE_URGENCIA';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FNC_JSON_PET';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FNC_VALIDA_SENHA_TUTOR';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_CLINICA';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_ESPECIE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_VETERINARIO';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_TUTOR';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_INSERT_PET';             EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --- 1.2 Views KURA (recriadas no BLOCO 5) ---
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_TIMELINE_PET';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_VACINAS_VENCENDO';   EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --- 1.3 Tabelas KURA + satelites da Sprint 1/2 (CASCADE CONSTRAINTS: ordem de FK dispensada) ---
-- Tabela de auditoria da Sprint 3 (nova e a da tentativa anterior)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_COBRANCA CASCADE CONSTRAINTS PURGE';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_AGENDAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Satelites academicos KURA da Sprint 1/2 (confirmados no schema; nao pertencem ao V19)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRESCRICAO_MEDICAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_SENHAS CASCADE CONSTRAINTS PURGE';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_CONSULTA CASCADE CONSTRAINTS PURGE';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- As 30 tabelas do schema V19 (nivel 5 -> nivel 1 da topologia de FK)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COBRANCA CASCADE CONSTRAINTS PURGE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONSULTA CASCADE CONSTRAINTS PURGE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXAME CASCADE CONSTRAINTS PURGE';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VACINA CASCADE CONSTRAINTS PURGE';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRESCRICAO CASCADE CONSTRAINTS PURGE';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOCUMENTO CASCADE CONSTRAINTS PURGE';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AGENDAMENTO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TRIAGEM_LUNA CASCADE CONSTRAINTS PURGE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALERTA_TEMPERATURA CASCADE CONSTRAINTS PURGE';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EVENTO_CLINICO CASCADE CONSTRAINTS PURGE';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTA_TUTOR CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TUTOR_PET CASCADE CONSTRAINTS PURGE';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTIFICACAO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INTERACAO_CANAL CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LEITURA_TEMPERATURA CASCADE CONSTRAINTS PURGE';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO_CLINICA CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONSENTIMENTO CASCADE CONSTRAINTS PURGE';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVITE_TUTOR CASCADE CONSTRAINTS PURGE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PET CASCADE CONSTRAINTS PURGE';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SERVICO_PRECO CASCADE CONSTRAINTS PURGE';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DISPOSITIVO_IOT CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VETERINARIO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TUTOR CASCADE CONSTRAINTS PURGE';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RACA CASCADE CONSTRAINTS PURGE';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE IDEMPOTENCY_KEY CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_ERRO CASCADE CONSTRAINTS PURGE';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIPO_EVENTO CASCADE CONSTRAINTS PURGE';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIE CASCADE CONSTRAINTS PURGE';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLINICA CASCADE CONSTRAINTS PURGE';              EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --- 1.4 Sequences KURA (as 29 do V19 + as da Sprint 3, nova e anterior) ---
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDITORIA_COBRANCA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDITORIA';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLINICA';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ESPECIE';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_EVENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RACA';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VETERINARIO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TUTOR';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PET';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INVITE_TUTOR';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVENTO_CLINICO';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICAMENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NOTIFICACAO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DISPOSITIVO_IOT';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LEITURA_TEMP';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTA_TEMP';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TRIAGEM_LUNA';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EXAME';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VACINA';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRESCRICAO';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOCUMENTO';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONSULTA';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOG_ERRO';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INTERACAO_CANAL';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO_CLINICA';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SERVICO_PRECO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COBRANCA';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTA_TUTOR';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONSENTIMENTO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AGENDAMENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IDEMPOTENCY_KEY';    EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT === BLOCO 1: limpeza concluida ===


-- #############################################################################
-- #  BLOCO 2 - SEQUENCES (29)
-- #
-- #  Finalidade: geradores de PK. Criados ANTES das tabelas porque 26 das 30
-- #  tabelas referenciam a sequence na expressao DEFAULT da PK
-- #  (DEFAULT SEQ_X.NEXTVAL - sintaxe Oracle 12c+, confirmada disponivel na
-- #  SD-01 contra o Oracle 19c da FIAP).
-- #
-- #  START WITH 100: convencao herdada das migrations V1/V12 - fica acima do
-- #  maior ID usado pelos seeds de desenvolvimento e pelas linhas ja existentes
-- #  em producao, evitando colisao de PK.
-- #
-- #  TRES SEQUENCES SAO ORFAS DE PROPOSITO - SEQ_CONTA_TUTOR, SEQ_CONSENTIMENTO
-- #  e SEQ_IDEMPOTENCY_KEY: as tabelas correspondentes usam GENERATED BY DEFAULT
-- #  AS IDENTITY (padrao Java-owned) e ninguem puxa dessas sequences. Elas
-- #  existem no banco real (migration V1) e sao mantidas aqui por fidelidade -
-- #  um script que diverge do banco real vale menos na banca que uma incoerencia
-- #  explicada.
-- #
-- #  SEQ_AGENDAMENTO **NAO** e orfa: embora ID_AGENDAMENTO seja IDENTITY no
-- #  banco, a entidade JPA Agendamento.java declara
-- #  @GeneratedValue(strategy = SEQUENCE, generator = "seq_agendamento") e puxa
-- #  desta sequence. As duas coisas coexistem porque GENERATED BY DEFAULT
-- #  (diferente de GENERATED ALWAYS) aceita valor explicito: o Hibernate fornece
-- #  o numero da sequence e o Oracle o respeita.
-- #############################################################################

PROMPT
PROMPT === BLOCO 2: sequences ===

-- --- 2.1 Sequences .NET-owned das tabelas nascidas na V1 (migration V12) ---
CREATE SEQUENCE SEQ_CLINICA        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESPECIE        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_EVENTO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RACA           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VETERINARIO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TUTOR          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PET            START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVITE_TUTOR   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENTO_CLINICO START WITH 100 INCREMENT BY 1;

-- --- 2.2 Sequences .NET-owned das tabelas nascidas na V9 (migration V12) ---
-- SEQ_LEITURA_TEMP / SEQ_ALERTA_TEMP: nomes abreviados vem literalmente das
-- *Configuration.cs do backend .NET - nao "corrigir" para o nome por extenso.
CREATE SEQUENCE SEQ_MEDICAMENTO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICACAO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISPOSITIVO_IOT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEITURA_TEMP    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA_TEMP     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRIAGEM_LUNA    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXAME           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VACINA          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESCRICAO      START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOCUMENTO       START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSULTA        START WITH 100 INCREMENT BY 1;

-- --- 2.3 Sequence de LOG_ERRO (migration V13) ---
CREATE SEQUENCE SEQ_LOG_ERRO       START WITH 100 INCREMENT BY 1;

-- --- 2.4 Sequence de INTERACAO_CANAL (migration V15) ---
CREATE SEQUENCE SEQ_INTERACAO_CANAL START WITH 100 INCREMENT BY 1;

-- --- 2.5 Sequence de USUARIO_CLINICA (migration V17) ---
CREATE SEQUENCE SEQ_USUARIO_CLINICA START WITH 100 INCREMENT BY 1;

-- --- 2.6 Sequences do modulo financeiro (migration V18) ---
CREATE SEQUENCE SEQ_SERVICO_PRECO  START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COBRANCA       START WITH 100 INCREMENT BY 1;

-- --- 2.7 Sequences Java-owned da V1 - SEQ_AGENDAMENTO e usada; as outras 3
--         sao orfas de proposito (ver cabecalho do BLOCO 2) ---
CREATE SEQUENCE SEQ_CONTA_TUTOR     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSENTIMENTO   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AGENDAMENTO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IDEMPOTENCY_KEY START WITH 100 INCREMENT BY 1;

PROMPT === BLOCO 2: 29 sequences criadas ===
