CREATE SEQUENCE SEQ_CLINICA          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VETERINARIO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TUTOR            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESPECIE          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RACA             START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PET              START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_EVENTO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EVENTO_CLINICO   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONSULTA         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VACINA           START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MEDICAMENTO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRESCRICAO       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EXAME            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DOCUMENTO        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AGENDAMENTO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTIFICACAO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONTA_TUTOR      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONSENTIMENTO    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOG_ERRO         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DISPOSITIVO_IOT  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LEITURA_TEMP     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERTA_TEMP      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRIAGEM_LUNA     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_IDEMPOTENCY_KEY  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVITE_TUTOR     START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CLINICA (
    ID_CLINICA       NUMBER(10)       DEFAULT SEQ_CLINICA.NEXTVAL NOT NULL,
    NM_CLINICA       VARCHAR2(120)    NOT NULL,
    NR_CNPJ          VARCHAR2(18)     NOT NULL,
    NM_RAZAO_SOCIAL  VARCHAR2(150),
    DS_ENDERECO      VARCHAR2(200)    NOT NULL,
    NM_CIDADE        VARCHAR2(80)     NOT NULL,
    SG_UF            CHAR(2)          NOT NULL,
    NR_CEP           VARCHAR2(9)      NOT NULL,
    DS_TELEFONE      VARCHAR2(20),
    DS_EMAIL         VARCHAR2(120)    NOT NULL,
    DT_CADASTRO      TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    ST_ATIVA         CHAR(1)          DEFAULT 'S' NOT NULL,
    DS_EMAIL_ACESSO  VARCHAR2(120)    NOT NULL,
    DS_SENHA_HASH    VARCHAR2(256)    NOT NULL,
    CONSTRAINT PK_CLINICA             PRIMARY KEY (ID_CLINICA),
    CONSTRAINT UK_CLINICA_CNPJ        UNIQUE (NR_CNPJ),
    CONSTRAINT UK_CLINICA_EMAIL_ACESSO UNIQUE (DS_EMAIL_ACESSO),
    CONSTRAINT CK_CLINICA_ATIVA       CHECK (ST_ATIVA IN ('S','N')),
    CONSTRAINT CK_CLINICA_UF          CHECK (LENGTH(SG_UF) = 2)
);

CREATE TABLE ESPECIE (
    ID_ESPECIE    NUMBER(5)      DEFAULT SEQ_ESPECIE.NEXTVAL NOT NULL,
    NM_ESPECIE    VARCHAR2(200)  NOT NULL,
    DT_CRIACAO    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT PK_ESPECIE      PRIMARY KEY (ID_ESPECIE),
    CONSTRAINT UK_ESPECIE_NOME UNIQUE (NM_ESPECIE)
);

CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO    NUMBER(10)     DEFAULT SEQ_MEDICAMENTO.NEXTVAL NOT NULL,
    NM_MEDICAMENTO    VARCHAR2(200)  NOT NULL,
    DS_PRINCIPIO_ATIVO VARCHAR2(500) NOT NULL,
    DS_APRESENTACAO   VARCHAR2(500)  NOT NULL,
    DT_CRIACAO        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO    TIMESTAMP,
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO)
);

CREATE TABLE TIPO_EVENTO (
    ID_TIPO_EVENTO  NUMBER(5)      DEFAULT SEQ_TIPO_EVENTO.NEXTVAL NOT NULL,
    CD_TIPO         VARCHAR2(20)   NOT NULL,
    NM_TIPO         VARCHAR2(200)  NOT NULL,
    DT_CRIACAO      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO  TIMESTAMP,
    CONSTRAINT PK_TIPO_EVENTO      PRIMARY KEY (ID_TIPO_EVENTO),
    CONSTRAINT UK_TIPO_EVENTO_CD   UNIQUE (CD_TIPO)
);

CREATE TABLE VETERINARIO (
    ID_VETERINARIO   NUMBER(10)     DEFAULT SEQ_VETERINARIO.NEXTVAL NOT NULL,
    ID_CLINICA       NUMBER(10)     NOT NULL,
    NM_VETERINARIO   VARCHAR2(200)  NOT NULL,
    NR_CRMV          VARCHAR2(20)   NOT NULL,
    DS_EMAIL         VARCHAR2(150)  NOT NULL,
    NR_TELEFONE      VARCHAR2(20)   NOT NULL,
    ST_ATIVO         CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_VETERINARIO PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT FK_VET_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_VET_CRMV    UNIQUE (NR_CRMV),
    CONSTRAINT UK_VET_EMAIL   UNIQUE (DS_EMAIL),
    CONSTRAINT CK_VET_ATIVO   CHECK (ST_ATIVO IN ('S','N'))
);

CREATE INDEX IDX_VET_CLINICA ON VETERINARIO(ID_CLINICA);

CREATE TABLE TUTOR (
    ID_TUTOR         NUMBER(10)     DEFAULT SEQ_TUTOR.NEXTVAL NOT NULL,
    ID_CLINICA       NUMBER(10)     NOT NULL,
    NM_TUTOR         VARCHAR2(200)  NOT NULL,
    NR_CPF           VARCHAR2(11)   NOT NULL,
    DT_NASCIMENTO    DATE,
    DS_EMAIL         VARCHAR2(150)  NOT NULL,
    NR_TELEFONE      VARCHAR2(20)   NOT NULL,
    DS_WHATSAPP      VARCHAR2(20),
    DS_ENDERECO      VARCHAR2(200),
    NM_CIDADE        VARCHAR2(80),
    SG_UF            CHAR(2),
    NR_CEP           VARCHAR2(9),
    ST_ATIVO         CHAR(1)        DEFAULT 'S' NOT NULL,
    ST_AVISO_PRIVACIDADE CHAR(1)    DEFAULT 'N' NOT NULL,
    DT_AVISO_PRIVACIDADE TIMESTAMP,
    DS_VERSAO_AVISO  VARCHAR2(20),
    DT_CRIACAO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_TUTOR         PRIMARY KEY (ID_TUTOR),
    CONSTRAINT FK_TUTOR_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_TUTOR_CPF     UNIQUE (NR_CPF),
    CONSTRAINT UK_TUTOR_EMAIL   UNIQUE (DS_EMAIL),
    CONSTRAINT CK_TUTOR_ATIVO   CHECK (ST_ATIVO IN ('S','N')),
    CONSTRAINT CK_TUTOR_AVISO   CHECK (ST_AVISO_PRIVACIDADE IN ('S','N'))
);

CREATE INDEX IDX_TUTOR_CLINICA ON TUTOR(ID_CLINICA);

CREATE TABLE RACA (
    ID_RACA          NUMBER(5)      DEFAULT SEQ_RACA.NEXTVAL NOT NULL,
    ID_ESPECIE       NUMBER(5)      NOT NULL,
    NM_RACA          VARCHAR2(200)  NOT NULL,
    DT_CRIACAO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_RACA         PRIMARY KEY (ID_RACA),
    CONSTRAINT FK_RACA_ESPECIE FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE),
    CONSTRAINT UK_RACA_ESPECIE UNIQUE (NM_RACA, ID_ESPECIE)
);

CREATE INDEX IDX_RACA_ESPECIE ON RACA(ID_ESPECIE);

CREATE TABLE PET (
    ID_PET               NUMBER(10)    DEFAULT SEQ_PET.NEXTVAL NOT NULL,
    ID_CLINICA           NUMBER(10)    NOT NULL,
    ID_ESPECIE           NUMBER(5)     NOT NULL,
    ID_RACA              NUMBER(5)     NOT NULL,
    ID_VETERINARIO_RESP  NUMBER(10),
    NM_PET               VARCHAR2(200) NOT NULL,
    DT_NASCIMENTO        DATE          NOT NULL,
    SG_SEXO              CHAR(1)       NOT NULL,
    SG_PORTE             CHAR(1)       NOT NULL,
    ST_ATIVO             CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO       TIMESTAMP,
    CONSTRAINT PK_PET             PRIMARY KEY (ID_PET),
    CONSTRAINT FK_PET_CLINICA     FOREIGN KEY (ID_CLINICA)         REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_PET_ESPECIE     FOREIGN KEY (ID_ESPECIE)         REFERENCES ESPECIE(ID_ESPECIE),
    CONSTRAINT FK_PET_RACA        FOREIGN KEY (ID_RACA)            REFERENCES RACA(ID_RACA),
    CONSTRAINT FK_PET_VETERINARIO FOREIGN KEY (ID_VETERINARIO_RESP) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CK_PET_SEXO        CHECK (SG_SEXO  IN ('M','F')),
    CONSTRAINT CK_PET_PORTE       CHECK (SG_PORTE IN ('P','M','G')),
    CONSTRAINT CK_PET_ATIVO       CHECK (ST_ATIVO IN ('S','N'))
);

CREATE INDEX IDX_PET_CLINICA     ON PET(ID_CLINICA);
CREATE INDEX IDX_PET_ESPECIE     ON PET(ID_ESPECIE);
CREATE INDEX IDX_PET_RACA        ON PET(ID_RACA);
CREATE INDEX IDX_PET_VETERINARIO ON PET(ID_VETERINARIO_RESP);

CREATE TABLE TUTOR_PET (
    ID_TUTOR     NUMBER(10)    NOT NULL,
    ID_PET       NUMBER(10)    NOT NULL,
    DS_VINCULO   VARCHAR2(50)  DEFAULT 'PROPRIETARIO' NOT NULL,
    ST_PRINCIPAL CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_VINCULO   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TUTOR_PET       PRIMARY KEY (ID_TUTOR, ID_PET),
    CONSTRAINT FK_TUTOR_PET_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_TUTOR_PET_PET   FOREIGN KEY (ID_PET)   REFERENCES PET(ID_PET),
    CONSTRAINT CK_TP_PRINCIPAL    CHECK (ST_PRINCIPAL IN ('S','N'))
);

CREATE INDEX IDX_TP_PET ON TUTOR_PET(ID_PET);

CREATE TABLE EVENTO_CLINICO (
    ID_EVENTO        NUMBER(10)    DEFAULT SEQ_EVENTO_CLINICO.NEXTVAL NOT NULL,
    ID_CLINICA       NUMBER(10)    NOT NULL,
    ID_PET           NUMBER(10)    NOT NULL,
    ID_VETERINARIO   NUMBER(10)    NOT NULL,
    ID_TIPO_EVENTO   NUMBER(5)     NOT NULL,
    DT_EVENTO        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DS_OBSERVACAO    VARCHAR2(1000) NOT NULL,
    DT_CRIACAO       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_EVENTO_CLINICO PRIMARY KEY (ID_EVENTO),
    CONSTRAINT FK_EV_CLINICA     FOREIGN KEY (ID_CLINICA)      REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_EV_PET         FOREIGN KEY (ID_PET)          REFERENCES PET(ID_PET),
    CONSTRAINT FK_EV_VETERINARIO FOREIGN KEY (ID_VETERINARIO)  REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT FK_EV_TIPO        FOREIGN KEY (ID_TIPO_EVENTO)  REFERENCES TIPO_EVENTO(ID_TIPO_EVENTO)
);

CREATE INDEX IDX_EV_CLINICA     ON EVENTO_CLINICO(ID_CLINICA);
CREATE INDEX IDX_EV_PET         ON EVENTO_CLINICO(ID_PET);
CREATE INDEX IDX_EV_VETERINARIO ON EVENTO_CLINICO(ID_VETERINARIO);
CREATE INDEX IDX_EV_TIPO        ON EVENTO_CLINICO(ID_TIPO_EVENTO);
CREATE INDEX IDX_EV_DATA        ON EVENTO_CLINICO(DT_EVENTO DESC);

CREATE TABLE CONSULTA (
    ID_CONSULTA      NUMBER(10)    DEFAULT SEQ_CONSULTA.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO NUMBER(10)   NOT NULL,
    DS_MOTIVO        VARCHAR2(200) NOT NULL,
    DS_ANAMNESE      VARCHAR2(2000),
    DS_EXAME_FISICO  VARCHAR2(2000),
    DS_DIAGNOSTICO   VARCHAR2(1000),
    DT_CONSULTA      TIMESTAMP     NOT NULL,
    ST_ATIVA         CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_CONSULTA         PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT FK_CONSULTA_EVENTO  FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT UK_CONSULTA_EVENTO  UNIQUE (ID_EVENTO_CLINICO),
    CONSTRAINT CK_CONSULTA_ATIVA   CHECK (ST_ATIVA IN ('S','N'))
);

CREATE TABLE VACINA (
    ID_VACINA          NUMBER(10)    DEFAULT SEQ_VACINA.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)    NOT NULL,
    NM_VACINA          VARCHAR2(200) NOT NULL,
    NR_LOTE            VARCHAR2(50)  NOT NULL,
    DS_FABRICANTE      VARCHAR2(200) NOT NULL,
    DT_PROXIMA_DOSE    TIMESTAMP,
    DT_CRIACAO         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_VACINA        PRIMARY KEY (ID_VACINA),
    CONSTRAINT FK_VACINA_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);

CREATE TABLE PRESCRICAO (
    ID_PRESCRICAO      NUMBER(10)    DEFAULT SEQ_PRESCRICAO.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)    NOT NULL,
    ID_MEDICAMENTO     NUMBER(10)    NOT NULL,
    DS_POSOLOGIA       VARCHAR2(500) NOT NULL,
    NR_DURACAO_DIAS    NUMBER(4)     NOT NULL,
    DT_CRIACAO         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_PRESCRICAO       PRIMARY KEY (ID_PRESCRICAO),
    CONSTRAINT FK_PRESC_EVENTO     FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT FK_PRESC_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO)   REFERENCES MEDICAMENTO(ID_MEDICAMENTO),
    CONSTRAINT CK_PRESC_DURACAO    CHECK (NR_DURACAO_DIAS > 0)
);

CREATE TABLE EXAME (
    ID_EXAME           NUMBER(10)     DEFAULT SEQ_EXAME.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)     NOT NULL,
    NM_EXAME           VARCHAR2(200)  NOT NULL,
    DS_RESULTADO       VARCHAR2(1000) NOT NULL,
    DT_REALIZACAO      DATE           NOT NULL,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_EXAME        PRIMARY KEY (ID_EXAME),
    CONSTRAINT FK_EXAME_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);

CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO       NUMBER(10)    DEFAULT SEQ_DOCUMENTO.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)    NOT NULL,
    NM_ARQUIVO         VARCHAR2(200) NOT NULL,
    DS_TIPO_MIME       VARCHAR2(100) NOT NULL,
    DS_CAMINHO         VARCHAR2(500) NOT NULL,
    NR_TAMANHO_BYTES   NUMBER(15)    NOT NULL,
    DT_CRIACAO         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_DOCUMENTO   PRIMARY KEY (ID_DOCUMENTO),
    CONSTRAINT FK_DOC_EVENTO  FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);

CREATE INDEX IDX_DOC_EVENTO ON DOCUMENTO(ID_EVENTO_CLINICO);

CREATE TABLE NOTIFICACAO (
    ID_NOTIFICACAO   NUMBER(10)     DEFAULT SEQ_NOTIFICACAO.NEXTVAL NOT NULL,
    ID_CLINICA       NUMBER(10)     NOT NULL,
    ID_TUTOR         NUMBER(10),
    ID_VETERINARIO   NUMBER(10),
    DS_TITULO        VARCHAR2(200)  NOT NULL,
    DS_MENSAGEM      VARCHAR2(500)  NOT NULL,
    ST_LIDA          CHAR(1)        NOT NULL,
    DT_LEITURA       TIMESTAMP,
    DT_CRIACAO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_NOTIFICACAO        PRIMARY KEY (ID_NOTIFICACAO),
    CONSTRAINT FK_NOTIF_CLINICA      FOREIGN KEY (ID_CLINICA)    REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_NOTIF_TUTOR        FOREIGN KEY (ID_TUTOR)      REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_NOTIF_VETERINARIO  FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CK_NOTIF_LIDA         CHECK (ST_LIDA IN ('S','N'))
);

CREATE INDEX IDX_NOTIF_CLINICA ON NOTIFICACAO(ID_CLINICA);
CREATE INDEX IDX_NOTIF_TUTOR   ON NOTIFICACAO(ID_TUTOR);

CREATE TABLE DISPOSITIVO_IOT (
    ID_DISPOSITIVO   NUMBER(10)    DEFAULT SEQ_DISPOSITIVO_IOT.NEXTVAL NOT NULL,
    ID_CLINICA       NUMBER(10)    NOT NULL,
    CD_DISPOSITIVO   VARCHAR2(20)  NOT NULL,
    DS_DESCRICAO     VARCHAR2(500) NOT NULL,
    DS_LOCALIZACAO   VARCHAR2(500) NOT NULL,
    DT_CRIACAO       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_DISPOSITIVO_IOT   PRIMARY KEY (ID_DISPOSITIVO),
    CONSTRAINT FK_IOT_CLINICA       FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_IOT_CD_DISPOSITIVO UNIQUE (CD_DISPOSITIVO)
);

CREATE INDEX IDX_IOT_CLINICA ON DISPOSITIVO_IOT(ID_CLINICA);

CREATE TABLE LEITURA_TEMPERATURA (
    ID_LEITURA          NUMBER(15)    DEFAULT SEQ_LEITURA_TEMP.NEXTVAL NOT NULL,
    ID_DISPOSITIVO_IOT  NUMBER(10)    NOT NULL,
    VL_TEMPERATURA      NUMBER(5,2)   NOT NULL,
    VL_UMIDADE          NUMBER(5,2),
    DT_LEITURA          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_CRIACAO          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP,
    CONSTRAINT PK_LEITURA_TEMP  PRIMARY KEY (ID_LEITURA),
    CONSTRAINT FK_LEITURA_DISP  FOREIGN KEY (ID_DISPOSITIVO_IOT) REFERENCES DISPOSITIVO_IOT(ID_DISPOSITIVO),
    CONSTRAINT CK_LEITURA_RANGE CHECK (VL_TEMPERATURA BETWEEN -40 AND 80)
);

CREATE INDEX IDX_LEITURA_DISP_DATA ON LEITURA_TEMPERATURA(ID_DISPOSITIVO_IOT, DT_LEITURA DESC);

CREATE TABLE ALERTA_TEMPERATURA (
    ID_ALERTA              NUMBER(10)    DEFAULT SEQ_ALERTA_TEMP.NEXTVAL NOT NULL,
    ID_LEITURA_TEMPERATURA NUMBER(15)    NOT NULL,
    DS_TIPO_ALERTA         VARCHAR2(50)  NOT NULL,
    VL_LIMITE              NUMBER(5,2)   NOT NULL,
    DS_MENSAGEM            VARCHAR2(500) NOT NULL,
    ST_RESOLVIDO           CHAR(1)       DEFAULT 'N' NOT NULL,
    DT_CRIACAO             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO         TIMESTAMP,
    CONSTRAINT PK_ALERTA_TEMP      PRIMARY KEY (ID_ALERTA),
    CONSTRAINT FK_ALERTA_LEITURA   FOREIGN KEY (ID_LEITURA_TEMPERATURA) REFERENCES LEITURA_TEMPERATURA(ID_LEITURA),
    CONSTRAINT CK_ALERTA_RESOLVIDO CHECK (ST_RESOLVIDO IN ('S','N'))
);

CREATE INDEX IDX_ALERTA_LEITURA ON ALERTA_TEMPERATURA(ID_LEITURA_TEMPERATURA);
CREATE INDEX IDX_ALERTA_ATIVOS  ON ALERTA_TEMPERATURA(ST_RESOLVIDO, DT_CRIACAO DESC);

CREATE TABLE TRIAGEM_LUNA (
    ID_TRIAGEM          NUMBER(10)    DEFAULT SEQ_TRIAGEM_LUNA.NEXTVAL NOT NULL,
    ID_CLINICA          NUMBER(10)    NOT NULL,
    ID_TUTOR            NUMBER(10),
    ID_PET              NUMBER(10),
    DS_NIVEL_URGENCIA   VARCHAR2(20)  NOT NULL,
    DS_DESCRICAO        VARCHAR2(2000) NOT NULL,
    ST_ENCAMINHADO_VET  CHAR(1)       NOT NULL,
    DT_TRIAGEM          TIMESTAMP     NOT NULL,
    ST_ATIVA            CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP,
    CONSTRAINT PK_TRIAGEM_LUNA       PRIMARY KEY (ID_TRIAGEM),
    CONSTRAINT FK_TRIAGEM_CLINICA    FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_TRIAGEM_TUTOR      FOREIGN KEY (ID_TUTOR)   REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_TRIAGEM_PET        FOREIGN KEY (ID_PET)     REFERENCES PET(ID_PET),
    CONSTRAINT CK_TRIAGEM_ENCAM      CHECK (ST_ENCAMINHADO_VET IN ('S','N')),
    CONSTRAINT CK_TRIAGEM_ATIVA      CHECK (ST_ATIVA           IN ('S','N'))
);

CREATE INDEX IDX_TRIAGEM_CLINICA ON TRIAGEM_LUNA(ID_CLINICA);
CREATE INDEX IDX_TRIAGEM_PET     ON TRIAGEM_LUNA(ID_PET);

CREATE TABLE INVITE_TUTOR (
    ID_INVITE        NUMBER(10)    DEFAULT SEQ_INVITE_TUTOR.NEXTVAL NOT NULL,
    ID_TUTOR         NUMBER(10)    NOT NULL,
    NR_TOKEN         VARCHAR2(36)  NOT NULL,
    DT_EXPIRACAO     TIMESTAMP     NOT NULL,
    DS_CANAL         VARCHAR2(20)  NOT NULL,
    ST_UTILIZADO     CHAR(1)       DEFAULT 'N' NOT NULL,
    ST_ATIVO         CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_CRIACAO       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_INVITE_TUTOR   PRIMARY KEY (ID_INVITE),
    CONSTRAINT FK_INVITE_TUTOR   FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    CONSTRAINT UK_INVITE_TOKEN   UNIQUE (NR_TOKEN),
    CONSTRAINT CK_INVITE_CANAL   CHECK (DS_CANAL      IN ('WHATSAPP','EMAIL','SMS')),
    CONSTRAINT CK_INVITE_UTILIZ  CHECK (ST_UTILIZADO  IN ('S','N')),
    CONSTRAINT CK_INVITE_ATIVO   CHECK (ST_ATIVO      IN ('S','N'))
);

CREATE INDEX IDX_INVITE_TOKEN ON INVITE_TUTOR(NR_TOKEN);
CREATE INDEX IDX_INVITE_TUTOR ON INVITE_TUTOR(ID_TUTOR);

CREATE TABLE CONTA_TUTOR (
    ID_CONTA              NUMBER(10)    DEFAULT SEQ_CONTA_TUTOR.NEXTVAL NOT NULL,
    ID_TUTOR              NUMBER(10)    NOT NULL,
    DS_EMAIL_LOGIN        VARCHAR2(200) NOT NULL,
    DS_SENHA_HASH         VARCHAR2(256) NOT NULL,
    DS_SALT               VARCHAR2(64),
    DS_REFRESH_TOKEN_HASH VARCHAR2(256),
    DT_REFRESH_EXPIRA     TIMESTAMP,
    DT_CADASTRO           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ULTIMO_LOGIN       TIMESTAMP,
    NR_TENTATIVAS_LOGIN   NUMBER(2)     DEFAULT 0 NOT NULL,
    DT_BLOQUEIO           TIMESTAMP,
    ST_ATIVA              CHAR(1)       DEFAULT 'S' NOT NULL,
    ST_EMAIL_VERIFICADO   CHAR(1)       DEFAULT 'N' NOT NULL,
    DS_TOKEN_RESET        VARCHAR2(256),
    DT_TOKEN_EXPIRA       TIMESTAMP,
    ID_INVITE_USADO       NUMBER(10),
    CONSTRAINT PK_CONTA_TUTOR       PRIMARY KEY (ID_CONTA),
    CONSTRAINT FK_CONTA_TUTOR       FOREIGN KEY (ID_TUTOR)        REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_CONTA_INVITE      FOREIGN KEY (ID_INVITE_USADO) REFERENCES INVITE_TUTOR(ID_INVITE),
    CONSTRAINT UK_CONTA_TUTOR       UNIQUE (ID_TUTOR),
    CONSTRAINT UK_CONTA_EMAIL       UNIQUE (DS_EMAIL_LOGIN),
    CONSTRAINT UK_CONTA_INVITE_USED UNIQUE (ID_INVITE_USADO),
    CONSTRAINT CK_CONTA_ATIVA       CHECK (ST_ATIVA             IN ('S','N')),
    CONSTRAINT CK_CONTA_EMAIL_VERIF CHECK (ST_EMAIL_VERIFICADO  IN ('S','N')),
    CONSTRAINT CK_CONTA_TENTATIVAS  CHECK (NR_TENTATIVAS_LOGIN BETWEEN 0 AND 99)
);

CREATE TABLE CONSENTIMENTO (
    ID_CONSENTIMENTO   NUMBER(10)    DEFAULT SEQ_CONSENTIMENTO.NEXTVAL NOT NULL,
    ID_TUTOR           NUMBER(10)    NOT NULL,
    DS_TIPO            VARCHAR2(100) NOT NULL,
    NR_VERSAO_TERMO    VARCHAR2(20)  NOT NULL,
    ST_ACEITO          CHAR(1)       NOT NULL,
    DT_CONSENTIMENTO   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CONSENTIMENTO PRIMARY KEY (ID_CONSENTIMENTO),
    CONSTRAINT FK_CONS_TUTOR    FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT CK_CONS_ACEITO   CHECK (ST_ACEITO IN ('S','N'))
);

CREATE INDEX IDX_CONS_TUTOR ON CONSENTIMENTO(ID_TUTOR);

CREATE TABLE AGENDAMENTO (
    ID_AGENDAMENTO       NUMBER(10)    DEFAULT SEQ_AGENDAMENTO.NEXTVAL NOT NULL,
    ID_CLINICA           NUMBER(10)    NOT NULL,
    ID_TUTOR             NUMBER(10),
    ID_PET               NUMBER(10),
    ID_VETERINARIO       NUMBER(10),
    NM_PACIENTE          VARCHAR2(200),
    DT_AGENDAMENTO       TIMESTAMP     NOT NULL,
    NR_DURACAO_MINUTOS   NUMBER(4),
    DS_SERVICO           VARCHAR2(500),
    DS_TIPO_CONSULTA     VARCHAR2(200),
    ST_STATUS            VARCHAR2(50),
    DS_STATUS            VARCHAR2(200),
    DS_ORIGEM            VARCHAR2(100),
    NR_VERSION           NUMBER(10)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AGENDAMENTO       PRIMARY KEY (ID_AGENDAMENTO),
    CONSTRAINT FK_AGEND_CLINICA     FOREIGN KEY (ID_CLINICA)     REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_AGEND_TUTOR       FOREIGN KEY (ID_TUTOR)       REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_AGEND_PET         FOREIGN KEY (ID_PET)         REFERENCES PET(ID_PET),
    CONSTRAINT FK_AGEND_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CK_AGEND_VERSION     CHECK (NR_VERSION >= 0)
);

CREATE INDEX IDX_AGEND_CLINICA ON AGENDAMENTO(ID_CLINICA);
CREATE INDEX IDX_AGEND_PET     ON AGENDAMENTO(ID_PET);
CREATE INDEX IDX_AGEND_DATA    ON AGENDAMENTO(DT_AGENDAMENTO);
CREATE INDEX IDX_AGEND_STATUS  ON AGENDAMENTO(ST_STATUS);

CREATE TABLE LOG_ERRO (
    ID_LOG            NUMBER(15)     DEFAULT SEQ_LOG_ERRO.NEXTVAL NOT NULL,
    NM_PROCEDURE      VARCHAR2(120)  NOT NULL,
    NM_USUARIO        VARCHAR2(60)   NOT NULL,
    DT_ERRO           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    NR_CODIGO_ERRO    NUMBER(10)     NOT NULL,
    DS_MENSAGEM_ERRO  VARCHAR2(2000) NOT NULL,
    DS_PARAMETROS     VARCHAR2(2000),
    DS_STACK_TRACE    CLOB,
    CONSTRAINT PK_LOG_ERRO PRIMARY KEY (ID_LOG)
);

CREATE INDEX IDX_LOG_DATA      ON LOG_ERRO(DT_ERRO DESC);
CREATE INDEX IDX_LOG_PROCEDURE ON LOG_ERRO(NM_PROCEDURE);

CREATE TABLE IDEMPOTENCY_KEY (
    ID_IDEMPOTENCY       NUMBER(10)    DEFAULT SEQ_IDEMPOTENCY_KEY.NEXTVAL NOT NULL,
    DS_KEY               VARCHAR2(64)  NOT NULL,
    NM_RESOURCE          VARCHAR2(60)  NOT NULL,
    ID_RESOURCE_CRIADO   NUMBER(10)    NOT NULL,
    DT_CRIACAO           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DT_EXPIRACAO         TIMESTAMP     NOT NULL,
    CONSTRAINT PK_IDEMPOTENCY_KEY    PRIMARY KEY (ID_IDEMPOTENCY),
    CONSTRAINT UK_IDEMPOTENCY_CHAVE  UNIQUE (DS_KEY, NM_RESOURCE),
    CONSTRAINT CK_IDEMPOTENCY_EXPIRA CHECK (DT_EXPIRACAO > DT_CRIACAO)
);

CREATE INDEX IDX_IDEMPOT_EXPIRA ON IDEMPOTENCY_KEY(DT_EXPIRACAO);

CREATE OR REPLACE VIEW VW_TIMELINE_PET AS
SELECT
    p.ID_PET,
    p.NM_PET,
    e.ID_EVENTO,
    te.NM_TIPO               AS NM_TIPO_EVENTO,
    e.DT_EVENTO,
    v.NM_VETERINARIO,
    e.DS_OBSERVACAO,
    te.CD_TIPO               AS CD_TIPO_EVENTO
FROM PET p
JOIN EVENTO_CLINICO e  ON e.ID_PET          = p.ID_PET
JOIN VETERINARIO    v  ON v.ID_VETERINARIO  = e.ID_VETERINARIO
JOIN TIPO_EVENTO   te  ON te.ID_TIPO_EVENTO = e.ID_TIPO_EVENTO
WHERE p.ST_ATIVO = 'S';

CREATE OR REPLACE VIEW VW_VACINAS_VENCENDO AS
SELECT
    p.ID_PET,
    p.NM_PET,
    t.ID_TUTOR,
    t.NM_TUTOR,
    t.DS_WHATSAPP,
    vac.NM_VACINA,
    vac.DT_PROXIMA_DOSE,
    (TRUNC(vac.DT_PROXIMA_DOSE) - TRUNC(SYSDATE)) AS DIAS_RESTANTES,
    c.NM_CLINICA
FROM VACINA vac
JOIN EVENTO_CLINICO e   ON e.ID_EVENTO   = vac.ID_EVENTO_CLINICO
JOIN PET            p   ON p.ID_PET      = e.ID_PET
JOIN TUTOR_PET      tp  ON tp.ID_PET     = p.ID_PET AND tp.ST_PRINCIPAL = 'S'
JOIN TUTOR          t   ON t.ID_TUTOR    = tp.ID_TUTOR
JOIN CLINICA        c   ON c.ID_CLINICA  = e.ID_CLINICA
WHERE vac.DT_PROXIMA_DOSE BETWEEN SYSTIMESTAMP AND SYSTIMESTAMP + INTERVAL '30' DAY
  AND p.ST_ATIVO = 'S';